### ISSUE TITLE
API management services should support multi region deployments

### ISSUE THREAD

**Issue by ArmaanMcleod** [Azure/PSRule.Rules.Azure#1030]
# Rule request

## Suggested rule change

API management services should support multi region deployments for globally distrubuted API consumers. 

## Applies to the following

The rule applies to the following:

- Resource type: **Microsoft.ApiManagement/service**

## Additional context

[Multi region deployments](https://docs.microsoft.com/en-us/azure/api-management/api-management-howto-deploy-multi-region)

**Comment by bengeset96** [comment]
This will be a cool rule to introduce. 

I'll take it.
