### ISSUE TITLE
Create automated PR workflow to bump providers.json

### ISSUE THREAD

**Issue by ArmaanMcleod** [Azure/PSRule.Rules.Azure#1041]
Create workflow to update `providers.json` automatically, preferrably with an automated PR from github actions that runs daily using a cron job. 

We could do a JSON diff between the current `providers.json` from the `main` branch and the REST API response data. For this diff to be reliable, we need to compare compressed JSON with sorted keys. 

If we find a change, we can run the `ExportProviders` task in `pipeline.build.ps1` in a new branch checked out from `main` and raise a PR.

**Comment by ArmaanMcleod** [comment]
I guess the other option is to run `ExportProviders` first, then see if any changes were picked up. I just think that could be unreliable since if properties are reordered or whitespace is added, it will count as a change. Probably unlikely this will happen but it could bring up false positivies.

**Comment by BernieWhite** [comment]
@ArmaanMcleod It's worth monitoring. I'm not noticing to much of that as there is some limited sorting already.
