### ISSUE TITLE
Automation accounts should enable diagnostic logs

### ISSUE THREAD

**Issue by ArmaanMcleod** [Azure/PSRule.Rules.Azure#1075]
# Rule request

Automation accounts should enable the following diagnostic logs:

- JobLogs
- JobStreams
- DSCNodeStatus
- Metrics

## Applies to the following

The rule applies to the following:

- Resource type: **Microsoft.Automation/automationAccounts**

## Additional context

[Template reference](https://docs.microsoft.com/en-us/azure/templates/microsoft.automation/automationaccounts?tabs=bicep)

**Comment by ArmaanMcleod** [comment]
@BernieWhite How did we want to create this rule. 

![autologs](https://user-images.githubusercontent.com/20082136/143681635-70b20e3d-91ae-403b-a2b3-75ce1aea5271.jpg)

Selecting the category group *allLogs* will enable all the following:

- JobLogs
- JobStreams
- DscNodeStatus
- AuditEvent

Selecting *auditLogs* will only enable `AuditEvent`.

Should we do something similar to AKS and create `Azure.Automation.PlatformLogs` and `Azure.Automation.AuditLogs` rules?

**Comment by BernieWhite** [comment]
@ArmaanMcleod Yes same as AKS ones. Keep audit separate.
