### ISSUE TITLE
Use Redis 6 for Azure Cache for Redis

### ISSUE THREAD

**Issue by BernieWhite** [Azure/PSRule.Rules.Azure#1077]
# Rule request

## Suggested rule change

Use the latest supported version of Redis with Azure Cache for Redis.

## Applies to the following

The rule applies to the following:

- Resource type: **Microsoft.Cache/Redis**

## Additional context

[Set Redis version for Azure Cache for Redis](https://docs.microsoft.com/en-gb/azure/azure-cache-for-redis/cache-how-to-version)

**Comment by ArmaanMcleod** [comment]
Unassigning myself from this one incase anyone else wants to have a go at this for a good first issue 🙂.

**Comment by dylan-apera** [comment]
I've created a rule and will run test against it. Steps remaining:
- Create a test to test the rule
- Take a copy of JSON deployment and run test against it
- Deploy Azure Cache for Redis and test against it (optional)
- Update documentation
