### ISSUE TITLE
IP address for public IP addresses directly attached to VMs

### ISSUE THREAD

**Issue by BernieWhite** [Azure/PSRule.Rules.Azure#11]
Check for public IP addresses attached directly to VMs.

**Comment by bengeset96** [comment]
@BernieWhite 

Could you explain why thils rule and what your expect out of this rule so I can contribute on it.

I might have a sense that it has something to do with Azure providing default outbound access IP when not attached, but want to be sure.

**Comment by lukemurraynz** [comment]
This rule should (if it's not already) reflect the upcoming changes to [Default outbound access in Azure.
.](https://learn.microsoft.com/azure/virtual-network/ip-services/default-outbound-access?WT.mc_id=AZ-MVP-5004796)

**Comment by BernieWhite** [comment]
Sorry for the late reply. I like the approach @BenjaminEngeset on PrivateSubnets.

Where I was going with this old issue was VMs should have public IPs. i.e.

- `Microsoft.Network/networkInterfaces` shouldn't reference a public IP via `properties.ipConfigurations[*].publicIPAddress`.

**Comment by BenjaminEngeset** [comment]
> Sorry for the late reply. I like the approach @BenjaminEngeset on PrivateSubnets.
> 
> Where I was going with this old issue was VMs should have public IPs. i.e.
> 
> * `Microsoft.Network/networkInterfaces` shouldn't reference a public IP via `properties.ipConfigurations[*].publicIPAddress`.

I understand. The `Azure.VNET.PrivateSubnet` doesn't solve what this initial issue was about, instead it actually work the quite opposite, recommending the explicit methods, which `Microsoft.Network/networkInterfaces` referencing a public IP via `properties.ipConfigurations[*].publicIPAddress` is.

I think the initial rule still makes sense as the recommended approach is to use a NAT gateway and by this rule, we are a step closer to that.

With `Azure.VNET.PrivateSubnet` we have removed the not recommended *implicit* method.

With `Azure.VM.PublicIP` or what it might be called we have removed one of the not recommended *explicit* methods and closer to the ultimate goal, using a NAT gateway.

What do you think?
