### ISSUE TITLE
Configure key auto-rotation in Azure Key Vault (preview)

### ISSUE THREAD

**Issue by ArmaanMcleod** [Azure/PSRule.Rules.Azure#1159]
# Rule request

## Suggested rule change

As shown here: https://docs.microsoft.com/en-us/azure/key-vault/keys/how-to-configure-key-rotation, automatic key rotation policies should be enabled. 

This is a preview feature. 

## Applies to the following

The rule applies to the following:

- Resource type: **Microsoft.KeyVault/vaults/keys**

## Additional context

[Key and secret management considerations in Azure](https://docs.microsoft.com/en-us/azure/architecture/framework/security/design-storage-keys#operational-considerations)

**Comment by ArmaanMcleod** [comment]
@BernieWhite Can probably create another rule for certificate autorotation.

**Comment by BernieWhite** [comment]
@ArmaanMcleod Auto-rotation of certificates is a little more challenging. It work for self-signed certificates which shouldn't be used anyway. A customers will get different experiences if they use integrated vs non-integrated CAs. I think the fact that certificates have a clear expiry built-in mitigates the issue.

For certs validity period is important. For keys and secrets setting an expiry is important.

**Comment by ArmaanMcleod** [comment]
@BernieWhite Agreed. I forgot about integrated vs non-integrated CAs 😄. I will just do auto rotation for keys, which should be doable. I think we can just check if a `rotationPolicy` exists in the resource and the action is set to `rotate`. Let me know what you think 🙂
