### ISSUE TITLE
Redis Enterprise cache minumum TLS version

### ISSUE THREAD

**Issue by ArmaanMcleod** [Azure/PSRule.Rules.Azure#1179]
# Rule request

## Suggested rule change

Similar to `Azure.Redis.MinTLS`, we should include `Microsoft.Cache/redisEnterprise` type as well to check the `minumumTlsVersion` property: https://docs.microsoft.com/en-us/azure/templates/microsoft.cache/redisenterprise?tabs=bicep#clusterproperties.

I guess we need to decide if this should be a new rule or simply add this type to the existing rule, given the property path is the same for both types. Makes sense to just add the type to the existing rule. 

## Applies to the following

The rule applies to the following:

- Resource type: **Microsoft.Cache/redisEnterprise**

## Additional context

[Data encryption in Azure](https://docs.microsoft.com/en-us/azure/architecture/framework/security/design-storage-encryption#data-in-transit)

**Comment by BernieWhite** [comment]
We should create this as a separate rule to give customers the option to individual suppress/ exclude rules. Also have a more specific example for the rule will help.
