### ISSUE TITLE
Create github workflow to automatically generate rule docs in PR

### ISSUE THREAD

**Issue by ArmaanMcleod** [Azure/PSRule.Rules.Azure#1260]
Following up from: https://github.com/Azure/PSRule.Rules.Azure/pull/1259#issuecomment-1040997298, It would be good to add a workflow to automatically build rule docs in a PR.

**Comment by BernieWhite** [comment]
Isn't this a dup of #1242?

**Comment by ArmaanMcleod** [comment]
@BernieWhite Ah didn't see that issue, will close this as dupe. Thanks for pointing that out.

**Comment by ArmaanMcleod** [comment]
Closing as dupe of #1242
