### ISSUE TITLE
Index was out of range with split on mock properties

### ISSUE THREAD

**Issue by bgawale** [Azure/PSRule.Rules.Azure#1327]
Facing an issue while expanding one of the bicep template that accepts NIC resource id and variables in the template are splitting the resource Id string to get the name of the NIC resource, works fine when deployed however expansion appears to be throwing an error below 

_An error occurred evaluating expression '[reference(resourceId('Microsoft.Network/networkInterfaces', variables('blob_nic_id_segments')[8]), '2020-11-01').ipConfigurations[0].properties.privateIPAddress]' line 0. Index was out of range. Must be non-negative and less than the size of the collection._

Here is a module of bicep that accepts NIC resource id as input and tries to get the NIC resource name using splits (We cannot input NIC name because of other dependencies of nested modules upstream). 

`param config_blob_nic_id string`
`param config_dfs_nic_id string`
`var blob_nic_id_segments = split(config_blob_nic_id, '/')`
`var dfs_nic_id_segments = split(config_dfs_nic_id, '/')`
`resource nic_blob_resource 'Microsoft.Network/networkInterfaces@2020-11-01' existing = {
  name: blob_nic_id_segments[8]
}`
`resource nic_dfs_resource 'Microsoft.Network/networkInterfaces@2020-11-01' existing = {
  name: dfs_nic_id_segments[8] 
}`
`var blob_nic_ip = nic_blob_resource.properties.ipConfigurations[0].properties.privateIPAddress `
`var dfs_nic_ip = nic_dfs_resource.properties.ipConfigurations[0].properties.privateIPAddress`

Note that we are compiling bicep template first so that it generates the json template and then getting it evaluated against PSRule.

**Comment by BernieWhite** [comment]
@bgawale Thanks for reporting the issue.

Can I ask if the network interfaces you are referencing are in the same bicep file your are trying to reference them from?

**Comment by bgawale** [comment]
thanks for the response, NICs are being provisioned from a different module but the module itself is the part of same master bicep template.

**Comment by BernieWhite** [comment]
@bgawale Also what version of PSRule for Azure are you using?

**Comment by bgawale** [comment]
Using module: PSRule - v1.11.1

**Comment by BernieWhite** [comment]
@bgawale No worries. This specific use case might be fixed by pre-release v1.14.0-B2203066.

Prior to version v1.14.0-B2203066, the behaviour was:

- When `reference` is called a mock object is returned instead of a real object, because the object isn't actually deployed to Azure by PSRule. This can be a problem for split operations because the contents of the property is different then what you expect. See [Limitations](https://azure.github.io/PSRule.Rules.Azure/expanding-source-files/#limitations). However we did improve this behaviour in the prerelease for properties that are set in the same bicep module or a related module in the deployment.
- Also there is an bug passing output from a module if you are using a output to feed the parameters `config_blob_nic_id` and `config_dfs_nic_id`.

There is another issue #1324 with the pre-release that I am working on that will be fixed in the next few days and it should be ready to try.

**Comment by bgawale** [comment]
Thanks for the quick response. We are using Install PSRule Azure DevOps extension activity to install the module. Any specific way to install this particular version using it?

steps:
- task: bewhite.ps-rule.install.ps-rule-install@1
  displayName: 'Install PSRule'
  inputs:
    module: PSRule.Rules.Azure
    prerelease: true
  timeoutInMinutes: 2
  retryCountOnTaskFailure: 2

**Comment by bgawale** [comment]
Just tried re-configuring with version mentioned above and ran the pipeline, still generates the same error for NICs.

**Comment by BernieWhite** [comment]
@bgawale Thanks for trying that. I'll see if I can reproduce the issue.

**Comment by BernieWhite** [comment]
@bgawale I've been able to reproduce the issue and I'm working on a fix.

**Comment by BernieWhite** [comment]
@bgawale I believe this issue should be fixed by pre-release v1.14.0-B2203117, but please double check and let us know.

**Comment by bgawale** [comment]
Thanks @BernieWhite - just ran a test with latest version i.e. 1.14.0-B2203117 and ran into almost similar issue which says 

> An error occurred evaluating expression '[reference(resourceId('Microsoft.Network/networkInterfaces', variables('dfs_nic_id_segments')[8]), '2020-11-01').ipConfigurations[0].properties.privateIPAddress]' line 0. The language expression index '8' is not valid for the object.

**Comment by BernieWhite** [comment]
@bgawale Ok thanks for giving that a go. Are you able to provide an example of how the parameters are being set in the parent module?

My test code looks like this:

**Parent module**

https://github.com/Azure/PSRule.Rules.Azure/blob/65409936821c8062accbd9350f7180400b13eeb1/tests/PSRule.Rules.Azure.Tests/Tests.Bicep.3.bicep#L4-L26

**Create private endpoint and NIC**

https://github.com/Azure/PSRule.Rules.Azure/blob/65409936821c8062accbd9350f7180400b13eeb1/tests/PSRule.Rules.Azure.Tests/Tests.Bicep.3.pe.bicep#L4-L27

**Use private IP**

https://github.com/Azure/PSRule.Rules.Azure/blob/65409936821c8062accbd9350f7180400b13eeb1/tests/PSRule.Rules.Azure.Tests/Tests.Bicep.3.dns.bicep#L4-L20

**Comment by bgawale** [comment]
Sure, here you go 
Main Template (part of it)
https://gist.github.com/bgawale/ca8bbb1ca13c067ff1e8b2c0c0752836#file-main-template

PE Module
https://gist.github.com/bgawale/38fa6ac4d31a9384edc5a5e96cb6bcc9

A Records Module (Part of it)
https://gist.github.com/bgawale/5a658ac2f2f9f4246177f446e3fbd903

**Comment by BernieWhite** [comment]
@bgawale Thanks. Struggling to get the samples to generate the error.

Are you able to update the example to generate the error.

I reconstructed this:

```bicep
var rgadb = resourceGroup(arm_adls_rg_name)
var arm_resource_location = resourceGroup().location
var arm_adls_name = 'dls123'
var arm_adls_rg_name = 'test-rg'
var arm_dbw_vnet_name = 'vnet-001'

resource arm_adb_vnet 'Microsoft.Network/virtualNetworks@2021-05-01' existing = {
  name: arm_dbw_vnet_name
}

module arm_pe_resource 'module-pe.bicep' = {
  name: 'arm_pe_resource'
  scope: rgadb
  params: {
    arm_adls_name: arm_adls_name
    arm_adls_rg_name: arm_adls_rg_name
    arm_dbw_vnet_name: arm_dbw_vnet_name
    arm_resource_location: arm_resource_location
  }
  dependsOn: [
    arm_adb_vnet
  ]
}

module a_records 'module-arecord.bicep' = {
  name: 'a_records'
  scope: rgadb
  params: {
    // arm_adls_name: arm_adls_name
    config_blob_nic_id: arm_pe_resource.outputs.blob_nic_id
    config_dfs_nic_id: arm_pe_resource.outputs.dfs_nic_id
  }
  dependsOn: [
    arm_pe_resource
  ]
}

```

```bicep
param arm_adls_name string
param arm_adls_rg_name string
param arm_dbw_vnet_name string
param arm_resource_location string

resource arm_adls_account 'Microsoft.Storage/storageAccounts@2021-08-01' existing = {
  name: arm_adls_name
}

resource adb_vnet_resource 'Microsoft.Network/virtualNetworks@2021-05-01' existing = {
  name: arm_dbw_vnet_name
}

resource pe_adls_blob_to_adb_name_resource 'Microsoft.Network/privateEndpoints@2020-11-01' = {
  name: 'pe_adls_blob_to_adb_name_resource'
  location: arm_resource_location
  properties: {
    privateLinkServiceConnections: [
      {
        name: 'pe-adls-blob-to-adb'
        properties: {
          privateLinkServiceId: arm_adls_account.id
          groupIds: [
            'blob'
          ]
        }
      }
    ]
    manualPrivateLinkServiceConnections: []
    subnet: {
      id: '${adb_vnet_resource.id}/subnets/default'
    }
    customDnsConfigs: []
  }
}

resource pe_adls_dfs_to_adb_name_resource 'Microsoft.Network/privateEndpoints@2020-11-01' = {
  name: 'pe_adls_dfs_to_adb_name_resource'
  location: arm_resource_location
  properties: {
    privateLinkServiceConnections: [
      {
        name: 'pe-adls-dfs-to-adb'
        properties: {
          privateLinkServiceId: arm_adls_account.id
          groupIds: [
            'dfs'
          ]
        }
      }
    ]
    manualPrivateLinkServiceConnections: []
    subnet: {
      id: '${adb_vnet_resource.id}/subnets/default'
    }
    customDnsConfigs: []
  }
}

output blob_nic_id string = pe_adls_blob_to_adb_name_resource.properties.networkInterfaces[0].id
output dfs_nic_id string = pe_adls_dfs_to_adb_name_resource.properties.networkInterfaces[0].id
```

```bicep
param config_blob_nic_id string
param config_dfs_nic_id string
param privateDnsZones_privatelink_blob_core_windows_net_name string = 'privatelink.blob.core.windows.net'
param privateDnsZones_privatelink_dfs_core_windows_net_name string = 'privatelink.dfs.core.windows.net'

var blob_nic_id_segments = split(config_blob_nic_id, '/')
var dfs_nic_id_segments = split(config_dfs_nic_id, '/')

resource nic_blob_resource 'Microsoft.Network/networkInterfaces@2020-11-01' existing = {
  name: blob_nic_id_segments[8]
}

resource nic_dfs_resource 'Microsoft.Network/networkInterfaces@2020-11-01' existing = {
  name: dfs_nic_id_segments[8]
}

resource dns_zone_blob_resource 'Microsoft.Network/privateDnsZones@2018-09-01' existing = {
  name: privateDnsZones_privatelink_blob_core_windows_net_name
  scope: resourceGroup()
}

resource dns_zone_dfs_resource 'Microsoft.Network/privateDnsZones@2018-09-01' existing = {
  name: privateDnsZones_privatelink_dfs_core_windows_net_name
  scope: resourceGroup()
}
```
