### ISSUE TITLE
Check for outer scope deployments using secure parameters

### ISSUE THREAD

**Issue by BernieWhite** [Azure/PSRule.Rules.Azure#1475]
# Rule request

## Suggested rule change

Deployments using an outer scope should not use any `secureObject` or `secureString` parameters.

## Applies to the following

The rule applies to the following:

- Resource type: **Microsoft.Resources/deployments**

## Additional context

[TTK test](https://github.com/Azure/arm-ttk/blob/master/arm-ttk/testcases/deploymentTemplate/Secure-Params-In-Nested-Deployments.test.ps1)

**Comment by ms-sambell** [comment]
Hey @BernieWhite,

Is this rule similar to : https://github.com/Azure/PSRule.Rules.Azure/blob/main/src/PSRule.Rules.Azure/rules/Azure.Deployment.Rule.ps1#L16 

But checking for a rendered `secureString|secureObject` parameters?
