### ISSUE TITLE
Bicep compilation timeout

### ISSUE THREAD

**Issue by Dylan-Prins** [Azure/PSRule.Rules.Azure#1507]
**Description of the issue**

When I am testing a lot of templates and starting other programs (like anthing from the office suite) the compilation of a template times out. I am compiling on a laptop with a Intel Core I7 (10th gen). Is it possible that the timeout is too short?

Templates do not have error or warnings

**Error output**

```text
Failed to expand parameter file 'C:\**\**\minimal.example.json'. Exception calling "GetResources" with "2" argument(s): "Bicep (0.8.2) compilation of 'C:\**\**\template.bicep' failed with: Bicep compilation hasn't completed within the timeout window. This can be caused by errors or warnings. Check the Bicep output by running bicep build and addressing any issues.
```

**Module in use and version:**

- Module: PSRule.Rules.Azure
- Version: **[e.g. 1.16.0]**

Captured output from `$PSVersionTable`:

```text

```

**Additional context**

**Comment by BernieWhite** [comment]
@Dylan-Prins The default interval can be too short particularly if you have a few levels of modules referencing modules or you are restore modules from a container registry.

You can configure the timeout be setting `AZURE_BICEP_FILE_EXPANSION_TIMEOUT`. See [Setup bicep](https://azure.github.io/PSRule.Rules.Azure/setup/setup-bicep/#configuringtimeout) to configure this setting.
