### ISSUE TITLE
Help link in Azure Devops Tests results

### ISSUE THREAD

**Issue by Dylan-Prins** [Azure/PSRule.Rules.Azure#1510]
**Is your feature request related to a problem? Please describe.**

It would help to have the help link in the test results of Azure DevOps
![image](https://user-images.githubusercontent.com/8777848/177358584-d64aa4f0-15d1-49e7-a220-8c99b50645aa.png)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by BernieWhite** [comment]
@Dylan-Prins Thanks for the suggestion.

**Comment by Dylan-Prins** [comment]
Works perfect with the switch!
