### ISSUE TITLE
Azure.VNET.UseNSGs is missing exceptions

### ISSUE THREAD

**Issue by VeraBE** [Azure/PSRule.Rules.Azure#1609]
# Rule request

## Suggested rule change

Azure.VNET.UseNSGs should also observe that NSGs cannot be added to RouteServerSubnet subnets: https://docs.microsoft.com/en-us/azure/route-server/route-server-faq#:~:text=No%2C%20Azure%20Route%20Server%20doesn%27t%20support%20NSG%20association%20to%20the%20RouteServerSubnet

Subnets that are delegated to a Dedicated HSM cannot have an NSG attached either: https://docs.microsoft.com/en-us/azure/dedicated-hsm/networking#:~:text=The%20subnet%20in%20which,on%20delegated%20subnets

**Comment by BernieWhite** [comment]
@VeraBE Good spot. Thanks for reporting the issue.
