### ISSUE TITLE
Review and update Front Door rule docs

### ISSUE THREAD

**Issue by BernieWhite** [Azure/PSRule.Rules.Azure#1667]
Review and update rule documentation with template and bicep examples.

Find documentation here: https://azure.github.io/PSRule.Rules.Azure/en/rules/resource/#front-door

Find source here: https://github.com/Azure/PSRule.Rules.Azure/tree/main/docs/en/rules

**Comment by lluppesms** [comment]
I think I'm done with these (at least - as done as I'm going to get! - I can't make the Hack tomorrow)
