### ISSUE TITLE
Container registry soft-delete

### ISSUE THREAD

**Issue by BernieWhite** [Azure/PSRule.Rules.Azure#1674]
# Rule request

## Suggested rule change

Currently soft-delete for container registries is a preview feature that keeps deleted artifacts for a soft-delete interval.

Soft-delete allows accidental actions to be recovered to restore a service otherwise relying on the artifacts that have been deleted.

There are a number of limitations with the feature currently. See [preview limitations](https://learn.microsoft.com/azure/container-registry/container-registry-soft-delete-policy#preview-limitations).

As a result, we shouldn't recommend this feature if a retention policy is configured or if we know that the registry is geo-replicated.

## Applies to the following

The rule applies to the following:

- Resource type: **Microsoft.ContainerRegistry/registries**

## Additional context

[CARML](https://github.com/Azure/ResourceModules/pull/2037#discussion_r974329513)
[Update](https://azure.microsoft.com/updates/public-preview-soft-delete-in-azure-container-registry/)
[Docs](https://learn.microsoft.com/azure/container-registry/container-registry-soft-delete-policy)
[Azure deployment reference](https://learn.microsoft.com/azure/templates/microsoft.containerregistry/registries#policies)

**Comment by bengeset96** [comment]
@BernieWhite 

Are you already working with this one? If not, I'd like to give it a try.

This is great news.

**Comment by BernieWhite** [comment]
@bengeset96 No. Feel free to pick this one up.
