### ISSUE TITLE
Use geo-replication for App Configuration stores

### ISSUE THREAD

**Issue by BernieWhite** [Azure/PSRule.Rules.Azure#1688]
# Rule request

## Suggested rule change

Enable replication for configuration stores to ensure that stores are **resilient** to region outages.

A replica is created by the `Microsoft.AppConfiguration/configurationStores/replicas` sub-resource.

This is a preview feature.

Currently this feature is not available on the free tier, so the rule should ignore free tier stores.

## Applies to the following

The rule applies to the following:

- Resource type: **Microsoft.AppConfiguration/configurationStores**

## Additional context

[Azure deployment reference](https://learn.microsoft.com/azure/templates/microsoft.appconfiguration/configurationstores/replicas)
[Geo replication](https://learn.microsoft.com/azure/azure-app-configuration/concept-geo-replication)

Related rules include:

- https://azure.github.io/PSRule.Rules.Azure/en/rules/Azure.ACR.GeoReplica/

**Comment by bengeset96** [comment]
I'd happily take it.

**Comment by bengeset96** [comment]
@BernieWhite 

For some reason, Europe regions are not supported with the Portal API. It's not really really a **big** concern, but some of our customers are heavily deploying in these regions. The documentation I've been able to find is even stating use cases for Europe. I have not checked other regions than US and Europe, so I'm unsure what the behaviour is in other regions.

https://learn.microsoft.com/en-us/azure/azure-app-configuration/concept-geo-replication

North Europe:
![image](https://user-images.githubusercontent.com/99641908/193114554-61b30f88-37e9-43d1-aace-3f7c3f6edb37.png)

East US:
![image](https://user-images.githubusercontent.com/99641908/193114665-16f770e9-3503-4518-b5bc-2649dc9556b9.png)

https://learn.microsoft.com/en-us/azure/azure-app-configuration/howto-geo-replication

Not stated here either as an limitation.

I will test with IaC, I assume most of the customers uses PSRule for Azure this way.

**Comment by bengeset96** [comment]
Works with IaC, but the child resource not visible in the portal there either.

**Comment by BernieWhite** [comment]
@bengeset96 I'd suggest that it is most likely due to the feature being in **preview**. I'm sure there would be a plan to expand region support but possibly not until GA. You're right the feature documentation is not clear about which regions are supported.
