### ISSUE TITLE
Enable purge protection for App Configuration stores

### ISSUE THREAD

**Issue by BernieWhite** [Azure/PSRule.Rules.Azure#1689]
# Rule request

## Suggested rule change

App Configuration supports purge protection to extend the protection provided by soft-delete. Purge protection limits data loss causes by accidental and malicious purges of deleted configuration stores by enforcing an mandatory retention interval.

This feature only applies to Standard SKU configuration stores. Free configuration stores should be ignored by this rule.

This is enabled by setting the `properties.enablePurgeProtection` property to `true`.

## Applies to the following

The rule applies to the following:

- Resource type: **Microsoft.AppConfiguration/configurationStores**

## Additional context

[Azure deployment reference](https://learn.microsoft.com/azure/templates/microsoft.appconfiguration/configurationstores)
[Purge protection](https://learn.microsoft.com/azure/azure-app-configuration/concept-soft-delete#purge-protection)

Related rules include:

- https://azure.github.io/PSRule.Rules.Azure/en/rules/Azure.KeyVault.PurgeProtect/

**Comment by bengeset96** [comment]
@ms-sambell 

If you are out of capacity or want to focus on other aspects, I'd happily help you out with this one.

**Comment by ms-sambell** [comment]
@bengeset96 That would be great, I'll assign it over to you. Thank you. :)
