### ISSUE TITLE
Audit App Configuration stores

### ISSUE THREAD

**Issue by BernieWhite** [Azure/PSRule.Rules.Azure#1690]
# Rule request

## Suggested rule change

Configuration stores provide diagnostics logs that can be configured to capture audit logs. Audit logs are required for determining which identities are reading configuration.

App Configuration uses the `Audit` category for audit logs.

## Applies to the following

The rule applies to the following:

- Resource type: **Microsoft.AppConfiguration/configurationStores**

## Additional context

[Azure deployment reference](https://learn.microsoft.com/azure/templates/microsoft.appconfiguration/configurationstores)

Related rules:

- https://azure.github.io/PSRule.Rules.Azure/en/rules/Azure.Automation.AuditLogs/

**Comment by bengeset96** [comment]
I'd happily take it.
