### ISSUE TITLE
Disable cryptographic keys for App Configuration stores

### ISSUE THREAD

**Issue by BernieWhite** [Azure/PSRule.Rules.Azure#1691]
# Rule request

## Suggested rule change

Configuration stores supports two authorization methods, access keys and Azure AAD identities. Using Azure AD identities centralizes identity management and auditing.

Access keys are disabled by setting the `properties.disableLocalAuth` property to `true`.

## Applies to the following

The rule applies to the following:

- Resource type: **Microsoft.AppConfiguration/configurationStores**

## Additional context

[Centralize all identity systems](https://learn.microsoft.com/azure/architecture/framework/security/design-identity-authentication#centralize-all-identity-systems)
[Azure deployment reference](https://learn.microsoft.com/azure/templates/microsoft.appconfiguration/configurationstores)
[Disable access key authentication for an Azure App Configuration instance](https://learn.microsoft.com/azure/azure-app-configuration/howto-disable-access-key-authentication)

Related rules include:

- https://azure.github.io/PSRule.Rules.Azure/en/rules/Azure.Cognitive.DisableLocalAuth/
- https://azure.github.io/PSRule.Rules.Azure/en/rules/Azure.EventGrid.DisableLocalAuth/

**Comment by pazdedav** [comment]
I am taking **AZR-000291** ID for this new rule.
