### ISSUE TITLE
Check for remote access using Azure Bastion in hub VNETs

### ISSUE THREAD

**Issue by BernieWhite** [Azure/PSRule.Rules.Azure#1761]
# Rule request

## Suggested rule change

VNETs with a GatewaySubnet also should have an AzureBastionSubnet to allow for out of band remote access to VMs.

Azure Bastion provides an extra layer of control. It enables secure and seamless RDP/SSH connectivity to your VMs directly from the Azure portal.

## Applies to the following

The rule applies to the following:

- Resource type: **Microsoft.Network/virtualNetworks**

## Additional context

[Plan for virtual machine remote access](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/plan-for-virtual-machine-remote-access)

**Comment by bengeset96** [comment]
I'd happily take it.

**Comment by bengeset96** [comment]
@BernieWhite 

Just to verify so we are alligned within our team.

The idea behind this rule is to limit the use of SSH/RDP over S2S or P2S VPN and instead rely on Azure Bastion that provides an extra layer of control?

If that's the case (I have limited knowledge with Azure Bastion and always tend to use `GNU/Linux jumpbox`), isn't still SSH/RDP allowed over the VPN gateway? Is there some configuration from MS when there both is existing a gateway subnet and a bastion subnet within a virtual network that will lock down the usage of SSH/RDP over VPN?

Thanks in advance.

**Comment by BernieWhite** [comment]
@bengeset96 Thanks for clarifying this. The main idea of the rule is:

**A `AzureBastionSubnet` should be added to any VNET which also has a `GatewaySubnet`.**

---

This is because:

- A `GatewaySubnet` signals a VNET hub.
- A bastion host acts as a security hardened jumpbox.
- The rule [Azure.NSG.LateralTraversal](https://azure.github.io/PSRule.Rules.Azure/en/rules/Azure.NSG.LateralTraversal/) already discourages use of general RDP/ SSH between VMs in Azure.

In terms of should you block access from on-premises to RDP or SSH, the guidance for the WAF specifically is not super clear on this aspect. The CAF specifically does suggest this.

For this rule lets focus on the `AzureBastionSubnet` part. Maybe blocking RDP/ SSH from on-premises is better suited to _PSRule for CAF_.

https://learn.microsoft.com/en-us/azure/architecture/framework/security/design-network-connectivity#on-premises-to-cloud-connectivity

**Comment by bengeset96** [comment]
@BernieWhite 

Thanks, then we are alligned and the purpose is clear.

This rule might have to be excluded for some customers, as `Azure Bastion` has cost that might not fit for everyone's budget, but they should atleast be aware, and that is exactly what this rule will achieve.

**Comment by bengeset96** [comment]
@BernieWhite 

Is it the correct understanding that subnets can be configured within `properties.subnets` or as a child resource?

I'm just trying to work my way into how to sauce this together. Should we only check for `properties.subnets` as we're targeting VNETs in a specific manner, or should we also check for child resources?

**Comment by BernieWhite** [comment]
@bengeset96 Yes you are correct.

The rule should be target to only run against the VNET resource. But since we are going to fail the VNET based on the `AzureBastionSubnet` not being present we should also check the sub-resources within the `resources` property of the VNET.

To perform this check you could aggregate the subnet names from `properties.subnets` and `Microsoft.Network/virtualNetworks/subnets` resources then check if `AzureBastionSubnet` is in the list.

**Comment by bengeset96** [comment]
Got it! 

You'll see a pull request from me once I've been able to put something representable together.
