### ISSUE TITLE
Add documentation around using PSRule for Azure with Bicep files that refers to private Bicep registries

### ISSUE THREAD

**Issue by bengeset96** [Azure/PSRule.Rules.Azure#1828]
**What is the path or URL of the page you're reporting?**

Don't know yet. Perhaps we should create a dedicated path for this.

**How could the page be improved?**

Add docoumentation around using PSRule for Azure with Bicep files that refers to private Bicep registries.

To deploy a module from a registry, you must have permission to pull the image.

Without setting up this correctly PSRule fails expanding the Bicep files that refers to private Bicep registries.

**Additional context**

Examples should also be added that supports GitHub and Azure DevOps.

**Comment by bengeset96** [comment]
@BernieWhite 

What do you think is the best approach here? Recommend customers using other actions and tasks with examples than ` microsoft/ps-rule@v2.4.2` and `ps-rule-assert@2` or that the action and task gets support to authenticate to the context (don't even know if this is possible in a short timeline)?

Bicep modules in Bicep registries has gotten quite popular and we should at least have some way to inform customers on how a working setup could look like.

**Comment by BernieWhite** [comment]
Does this address the requirement or do you think we need to add additional information here: https://azure.github.io/PSRule.Rules.Azure/using-bicep/#restoring-modules-from-a-private-registry

**Comment by bengeset96** [comment]
> registry

This issue can be closed. I was not even aware that documentation for this had been created. Very nice!

**Comment by bengeset96** [comment]
> Does this address the requirement or do you think we need to add additional information here: https://azure.github.io/PSRule.Rules.Azure/using-bicep/#restoring-modules-from-a-private-registry

This issue can be closed. I was aware this already was covered. Very nice!
