### ISSUE TITLE
Azure Database for MariaDB servers should meet naming requirements

### ISSUE THREAD

**Issue by BenjaminEngeset** [Azure/PSRule.Rules.Azure#1854]
# Rule request

## Suggested rule change

Azure Database for MariaDB servers should meet naming requirements.

Same goes for the child resources.

Operational Excellence pillar for this one.

## Applies to the following

The rule applies to the following:

- Resource type: **[Microsoft.DBforMariaDB/servers]**

## Additional context

[Naming rules and restrictions for Azure Database for MariaDB](https://learn.microsoft.com/azure/azure-resource-manager/management/resource-name-rules#microsoftdbformariadb)
[Template reference](https://learn.microsoft.com/azure/templates/microsoft.dbformariadb/servers)

**Comment by bengeset96** [comment]
@BernieWhite 

I've started to play little around with this rule. Do you think it could add additional value to have the rule also againt child resources as `Microsoft.DBforMariaDB/servers/databases`, `Microsoft.DBforMariaDB/servers/firewallRules`, `Microsoft.DBforMariaDB/servers/virtualNetworkRules`?

**Comment by BernieWhite** [comment]
@bengeset96 Naming of resources is often a cause of early deployment failures so anything we can do it reduce those is great.

I'd generally suggest that we create separate rules for each.
