### ISSUE TITLE
Azure Monitor agent should be installed on virtual machine scale sets

### ISSUE THREAD

**Issue by BenjaminEngeset** [Azure/PSRule.Rules.Azure#1867]
# Rule request

## Suggested rule change

Azure Monitor agent should be installed on virtual machine scale sets.

Defender for Cloud collects data from your Azure virtual machines (VMs) to monitor for security vulnerabilities and threats. Data is collected using the Azure Monitor Agent.

Security pillar for this one.

## Applies to the following

The rule applies to the following:

- Resource type: **[Microsoft.Compute/virtualMachineScaleSets]**

## Additional context

[Deploy the Azure Monitor Agent to protect your servers with Microsoft Defender for Cloud](https://learn.microsoft.com/en-us/azure/defender-for-cloud/auto-deploy-azure-monitoring-agent)
[Template reference](https://learn.microsoft.com/en-us/azure/templates/microsoft.compute/virtualmachinescalesets)

**Comment by BernieWhite** [comment]
@bengeset96 Good idea. Support for AMA is currently in preview for Microsoft Defender for Cloud, otherwise by default only non-security data is collected by default. So maybe let's flag this as preview for now.

**Comment by maxricketts** [comment]
This does also flag up when you are using build agent scale sets that get torn up and down with ephemeral disks and you would not want the agent to be installed in most cases

**Comment by BenjaminEngeset** [comment]
> This does also flag up when you are using build agent scale sets that get torn up and down with ephemeral disks and you would not want the agent to be installed in most cases

Thanks for the feedback @maxricketts. Yes and no I would like to say, there is fully possible to use an ephemeral disk for a short or long time of period on a virtual machine scale set. For customers it might be valuable to have information in this period and have the data collected available. When using public and private images it could also bring value to collect data and actively analyze it.

**Comment by BernieWhite** [comment]
Refocussing this on operational excellence based on #1927 discussion.

**Comment by BernieWhite** [comment]
@maxricketts I think in the general case most customers would expect that operational monitoring of Virtual Machine Scale Sets should be enabled.

However there would be exception cases where you may not want monitoring such as dev environments or special cases. For these you can suppress or exclude the rule on an as needed basis.

**Comment by mpr555** [comment]
@BernieWhite - Thank you for the feedback
