### ISSUE TITLE
Azure Monitor agent should be installed on virtual machines

### ISSUE THREAD

**Issue by BenjaminEngeset** [Azure/PSRule.Rules.Azure#1868]
# Rule request

## Suggested rule change

Azure Monitor agent should be installed on virtual machines.

Defender for Cloud collects data from your Azure virtual machines (VMs) to monitor for security vulnerabilities and threats. Data is collected using the Azure Monitor Agent.

Security pillar for this one.

## Applies to the following

The rule applies to the following:

- Resource type: **[Microsoft.Compute/virtualMachines]**

## Additional context

[Deploy the Azure Monitor Agent to protect your servers with Microsoft Defender for Cloud](https://learn.microsoft.com/en-us/azure/defender-for-cloud/auto-deploy-azure-monitoring-agent)
[Template reference](https://learn.microsoft.com/en-us/azure/templates/microsoft.compute/virtualmachines)

**Comment by BernieWhite** [comment]
@bengeset96 Good idea. Support for AMA is currently in preview for Microsoft Defender for Cloud, otherwise by default only non-security data is collected by default. So maybe let's flag this as preview for now.
