### ISSUE TITLE
Consider using Azure role-based access control for key vaults

### ISSUE THREAD

**Issue by BenjaminEngeset** [Azure/PSRule.Rules.Azure#1916]
# Rule request

## Suggested rule change

Key vaults supports Azure role-based access control that is an authorization system built on Azure Resource Manager that provides fine-grained access management.

Benefits to customers:

- Access control by using the same API across Azure services.
- Centralized access management.
- Can be integrated with PIM for time-based access control. 
- The ability to have separate permissions on individual keys, secrets, and certificates.

The Azure RBAC also includes some disadvantages that should be documented to customers as this can be a key important decision maker for which authorization system they should use.

I think this would fit nice into the Security pillar.

## Applies to the following

The rule applies to the following:

- Resource type: **[Microsoft.KeyVault/vaults]**

## Additional context

[Provide access to Key Vault keys, certificates, and secrets with an Azure role-based access control](https://learn.microsoft.com/azure/key-vault/general/rbac-guide)
[Template reference](https://learn.microsoft.com/azure/templates/microsoft.keyvault/vaults)

**Comment by BernieWhite** [comment]
@BenjaminEngeset This is a tricky one, there are a few cases where this does not work well around infrastructure as code.

**Comment by BenjaminEngeset** [comment]
@BernieWhite 

I understand. I assume you're thinking to the role assignments latency where access policies on the other hand are assigned instantly?

If you feel this is a bad call to point customers to, where it has more disadvantages with IaC than advantages, we can just have this floating around or consider to won't do.

**Comment by BernieWhite** [comment]
@BenjaminEngeset Exactly, configuring Bicep deployment that references multiple resources often requires something to be stored in Key Vault.

Maybe let's leave this issue open and see if there is interest in the issue.

**Comment by BenjaminEngeset** [comment]
@BernieWhite What do you think now given that this is the recommended authorization system for vaults?

I'm still unsure as it still has the same issues around infrastructure as code.

https://azure.microsoft.com/updates/key-vault-rbac-access-configuration

**Comment by BernieWhite** [comment]
@BenjaminEngeset Yep let's add a new rule as a warning for this.

There is still some limitations: https://learn.microsoft.com/azure/key-vault/general/rbac-access-policy#data-plane-access-control-recommendation
