### ISSUE TITLE
Ignore Azure.AKS.Version for clusters with auto-upgrade enabled

### ISSUE THREAD

**Issue by BernieWhite** [Azure/PSRule.Rules.Azure#1918]
# Rule request

## Suggested rule change

For managed clusters with auto-upgrade enabled (`rapid`/ `stable`/ `node-image`) the specific version installed for the cluster API server should be ignored unless the evaluation it occurring against an in-flight resource.

Update the existing `Azure.AKS.Version` rule to improve this behaviour.

## Applies to the following

The rule applies to the following:

- Resource type: **Microsoft.ContainerService/managedClusters**

**Comment by BenjaminEngeset** [comment]
I'd take it if you're not already working with it.

**Comment by BernieWhite** [comment]
@BenjaminEngeset Absolutely. I haven't started working on it.
