### ISSUE TITLE
Require event hub namespaces to use a minimum of TLS 1.2

### ISSUE THREAD

**Issue by BernieWhite** [Azure/PSRule.Rules.Azure#1995]
# Rule request

## Suggested rule change

Event hubs namespaces should require a minimum of TLS 1.2.

https://learn.microsoft.com/en-us/azure/event-hubs/transport-layer-security-enforce-minimum-version

## Applies to the following

The rule applies to the following:

- Resource type: **Microsoft.EventHub/namespaces**

## Additional context

- [Azure deployment reference](https://learn.microsoft.com/en-us/azure/templates/microsoft.eventhub/namespaces?pivots=deployment-language-bicep)

**Comment by BenjaminEngeset** [comment]
<--- :shipit:
