### ISSUE TITLE
Require IoT Hub to use a minimum of TLS 1.2

### ISSUE THREAD

**Issue by BernieWhite** [Azure/PSRule.Rules.Azure#1996]
# Rule request

## Suggested rule change

IoT Hubs should require a minimum of TLS 1.2.

However some important notes apply:

- Not all IoT devices support TLS 1.2.
- Also TLS 1.2 enforcement is currently only supported in a minimal number of regions as specified by https://learn.microsoft.com/en-us/azure/iot-hub/iot-hub-tls-support#tls-12-enforcement-available-in-select-regions.

## Applies to the following

The rule applies to the following:

- Resource type: **Microsoft.Devices/IotHubs**

## Additional context

- [Azure deployment reference](https://learn.microsoft.com/en-us/azure/templates/microsoft.devices/iothubs?pivots=deployment-language-bicep)

**Comment by BenjaminEngeset** [comment]
<--- :shipit:
