### ISSUE TITLE
No bicep processing with AZURE_PARAMETER_FILE_EXPANSION

### ISSUE THREAD

**Issue by khaliddermoumi** [Azure/PSRule.Rules.Azure#2044]
**Description of the issue**
As explained in ["Using parameter files" docs](https://azure.github.io/PSRule.Rules.Azure/using-bicep/#using-parameter-files), it should be possible to let PSRule discover a parameter file, and analyse the associated bicep file using the parameter file. This obviously does not work (at least in the versions stated below).

**To Reproduce**

Steps to reproduce the issue:

Here is an example.

```yaml
# file: ps-rule.yaml

include:
  module:
    - PSRule.Rules.Azure

requires:
  PSRule: '>=2.7.0'
  PSRule.Rules.Azure: '>=1.24.0'

configuration:
  AZURE_PARAMETER_FILE_EXPANSION: true
  AZURE_BICEP_FILE_EXPANSION: false

execution:
  suppressedRuleWarning: false
  notProcessedWarning: false
```

```bicep
// file: storage.bicep

@description('Storage Account type')
param storageAccountType string

@description('Location for the storage account.')
param location string = resourceGroup().location

@description('The name of the Storage Account')
param storageAccountName string = 'store${uniqueString(resourceGroup().id)}'

resource sa 'Microsoft.Storage/storageAccounts@2021-06-01' = {
    name: storageAccountName
    location: location
    sku: {
        name: storageAccountType
    }
    kind: 'StorageV2'
    properties: {}
}
```

```bicep
# file: storage.test.bicep

targetScope = 'resourceGroup'

param storageAccountType string
param location string = resourceGroup().location

@description('Minimum configuration.')

module sa 'storage.bicep' = {
    name: 'storage'
    params: {
        storageAccountType: storageAccountType
        location: location
    }
}
```

file below: "storage.test.parameters.json"
```json
{
  "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "storageAccountType": {
      "value": "Standard_LRS"
    }
  }
}
```

**Expected behaviour**

Now when you run PSRule, the bicep files should be analysed, and according rule processing messages should be printed by PSRule. 
This does not happen. Instead, PSRule does not print anything. Note that I also tried the usage of the "metadata"-attribute, as described in the docs, which made no difference.

When you instead reconfigure the files above with "AZURE_BICEP_FILE_EXPANSION: true" for regular bicep file expansion, PSRule performs as expected, and prints rule evaluations as expected.

How does this need to be configured, to have parameter file expansion plus analysing the associated bicep files, given the example above? To me, the configuration above looks ok (given the docs), so this looks like a bug.

**Module in use and version:**

- Module: PSRule.Rules.Azure
- Version: **1.24.2**

- Module: PSRule
- Version: **2.7.0**

Captured output from `$PSVersionTable`:

```text
Name                           Value
----                           -----
PSVersion                      7.3.2
PSEdition                      Core
GitCommitId                    7.3.2
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}       
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Additional context**

**Comment by BernieWhite** [comment]
@khaliddermoumi Thanks for raising the issue.

The example above does not include the `metadata` property. Are you able to try the following as per the instructions:

> Alternatively, you can choose to expand and test a Bicep module from JSON parameter files [by metadata](https://azure.github.io/PSRule.Rules.Azure/using-templates/#by-metadata).

```json
{
  "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#",
  "contentVersion": "1.0.0.0",
  "metadata": {
    "template": "./storage.bicep"
  },
  "parameters": {
    "storageAccountType": {
      "value": "Standard_LRS"
    }
  }
}
```

**Comment by khaliddermoumi** [comment]
> @khaliddermoumi Thanks for raising the issue.
> 
> The example above does not include the `metadata` property. Are you able to try the following as per the instructions:
> 
> > Alternatively, you can choose to expand and test a Bicep module from JSON parameter files [by metadata](https://azure.github.io/PSRule.Rules.Azure/using-templates/#by-metadata).
> (...)

Hi Bernie,
I also tried to use the "metadata" property, but it does not work too - in the same way, no bicep analysis.

> Alternatively for the `storage.tests.bicep` you can just set a default for `storageAccountType`. You can find some examples here: https://github.com/Azure/PSRule.Rules.Azure-quickstart/blob/main/bicep/modules/keyvault/v1/.tests/main.tests.bicep
> 
I would really prefer a lot to get it to run with parameter files, because we already have a lot of them. For our setup, we would need exactly this feature.

How do we get it to run?

**Comment by BernieWhite** [comment]
@khaliddermoumi Your `ps-rule.yaml` configuration is fine.

Are you able to provide some additional information:

- Are you using the DevOps extension tasks/ GitHub Action/ or PowerShell command-line?
- Are you able to provide a snippet of your pipeline or PowerShell command-line?
- Are you able to provide an example of the output?

**Comment by khaliddermoumi** [comment]
Hi,
I was using the PS CLI, and this command: "Invoke-PSRule -InputPath .".
Using your command line, I get the same output as you do - thanks a lot.
I was assuming "Invoke-PSRule -InputPath ." was ok, as this worked with the "bicep expansion".
So I see, the command was obviously the reason it didn't work.

Thanks a lot for your help!
