### ISSUE TITLE
Add support for jsonc extension

### ISSUE THREAD

**Issue by tectonia** [Azure/PSRule.Rules.Azure#2053]
I use jsonc extension to add comments and context to my parameters files. Currently it seems only json extension is supported. Would be great to see jsonc supported too.

**Comment by ReneRebsdorf** [comment]
@BernieWhite Any chance this could get some love?
I see you closed #2132 which you mention relates to this request for jsonc support?

While I can not speak for @tectonia ; but only for our teams sake: We prefer json(jsonc) files over bicepparams as we use the same parameters to automated documentation generation, and other functionality, where processing the commonly used and structured nature of json is superior to string parsing a bicepparams file.

jsonc support would resolve problems we are facing with other linters we use for our repos which doesnt like comments in regular json files, and commenting in json parameter files helps provide clarify in rationales for certain param values, and the likes.
