### ISSUE TITLE
Key Vaults should disable their public network

### ISSUE THREAD

**Issue by zilberd** [Azure/PSRule.Rules.Azure#2067]
### Suggested rule

I realized that some network rules concerning public endoint are implented in the storage and sql but not in Keyvaults.

I think we could have a check to see if KV has it firewall set to deny in order to push for stronger network intergration.
This is a recomandation of the security baseline
https://learn.microsoft.com/en-us/security/benchmark/azure/baselines/key-vault-security-baseline?context=%2Fazure%2Fkey-vault%2Fgeneral%2Fcontext%2Fcontext#disable-public-network-access

and can be implemented by the following azure policy
https://www.azadvertizer.net/azpolicyadvertizer/405c5871-3e91-4644-8a63-58e19d68ff5b.html

### Pillar

Security

### Additional context

Taking the next step woulf be to create a policiy check for Private endoint or disabling the trusted services cheks.

However, my experience is that trusted services integration is very usefull (eg: WAF, API managenement, ...) and therefor I won't push for more than recommending to only connect from trusted network.

After all Keyvault would still need a valid access policy to give access to any of its content.

**Comment by BenjaminEngeset** [comment]
I'd like to contribute on this one.

**Comment by zilberd** [comment]
Hi Benjamin, thank you very much.
we already have a PR running as I had the check ready to go. (this was a homemade check I am using)

**Comment by BenjaminEngeset** [comment]
> Hi Benjamin, thank you very much. we already have a PR running as I had the check ready to go. (this was a homemade check I am using)

Great and good work!
