### ISSUE TITLE
Container Apps should use volume mounts for to ensure availability of persistent storage capacity

### ISSUE THREAD

**Issue by BenjaminEngeset** [Azure/PSRule.Rules.Azure#2101]
### Suggested rule

Container Apps should use volume mounts for to ensure availability of persistent storage capacity.

Defaults to using its own container file system, which has no capacity guarantees. The available storage depends on the amount of disk space available in the container.

I guess that `Reliability` is better suited for this than `Operational Excellence` pillar, but open for feedback.

### Pillar

Reliability

### Additional context

- [Use storage mounts in Azure Container Apps](https://learn.microsoft.com/azure/container-apps/storage-mounts)
- [Azure deployment reference](https://learn.microsoft.com/azure/templates/microsoft.app/containerapps##volume)

**Comment by BernieWhite** [comment]
@BenjaminEngeset I agree Reliability is the best pillar for this.

---

We might need to give a bit of thought to this rule. Apps may require no storage, for example a stateless web API or a single page application (that just calls APIs).

So this rule should only target cases where storage is required. We shouldn't suggest to attach storage if it is not required.

**Comment by BenjaminEngeset** [comment]
@BernieWhite 

Agreed, I'll create some additional effort on the documentation and leets see what we think on the pull request.
