### ISSUE TITLE
Update Azure.ContainerApp* rules documentation

### ISSUE THREAD

**Issue by BenjaminEngeset** [Azure/PSRule.Rules.Azure#2103]
**Description of the issue**

Related to #2102 

During the month of March 2022, all Azure Container Apps resources will be gradually migrated from the Microsoft.Web namespace to the Microsoft.App namespace.

https://github.com/microsoft/azure-container-apps/issues/109

Examples in `Azure.ContainerApp.*.md` should be adjusted accordingly.

**Comment by BernieWhite** [comment]
All examples and rules have been migrated to the `Microsoft.App` resource provider. No further work required.
