### ISSUE TITLE
Check that Azure AD authentication is configured for SQL Managed Instance

### ISSUE THREAD

**Issue by BernieWhite** [Azure/PSRule.Rules.Azure#2117]
### Suggested rule

To SQL managed instance can have Azure AD authentication configured similar to SQL DB (`Azure.SQL.AAD`). Azure AD authentication should be used instead of SQL logins.

### Pillar

Security

### Additional context

- https://learn.microsoft.com/azure/azure-sql/database/authentication-azure-ad-only-authentication
- https://learn.microsoft.com/azure/azure-sql/database/authentication-aad-configure

Manged identity is required for this feature in SQL MI.

> You must enable the instance identity (SMI or UMI) to allow support for Azure AD authentication in SQL Managed Instance. For SQL Database, enabling the server identity is optional and required only if an Azure AD service principal (Azure AD application) oversees creating and managing Azure AD users, groups, or applications in the server. For more information, see [Azure Active Directory service principal with Azure SQL](https://learn.microsoft.com/azure/azure-sql/database/authentication-aad-service-principal?view=azuresql-mi).

**Comment by BenjaminEngeset** [comment]
Great, you'll see something at PR soon.

**Comment by BernieWhite** [comment]
@BenjaminEngeset Like `Azure.SQL.AAD` in that AAD auth is enabled. AAD only accepted is a separate rule (#2118) so that customers can suppress separately if required.

**Comment by BenjaminEngeset** [comment]
> @BenjaminEngeset Like `Azure.SQL.AAD` in that AAD auth is enabled. AAD only accepted is a separate rule (#2118) so that customers can suppress separately if required.

Perfect, I did not see that one, then it makes all sense!
