### ISSUE TITLE
Use a VM maintenance configuration for virtual machines (preview)

### ISSUE THREAD

**Issue by BernieWhite** [Azure/PSRule.Rules.Azure#2121]
### Suggested rule

VMs can be assigned a maintenance configuration which allows managed assessments and updates for VM patches within the guest operating system.

This can be done by creating a `Microsoft.Maintenance/configurationAssignments` sub resource with the linked maintenance configuration resource Id.

For in-flight resources we need to collect and export this data.

### Pillar

Operational Excellence

### Additional context

- https://learn.microsoft.com/azure/templates/microsoft.maintenance/configurationassignments
- https://learn.microsoft.com/azure/update-center/manage-vms-programmatically
- https://learn.microsoft.com/azure/update-center/manage-update-settings

**Comment by BenjaminEngeset** [comment]
I can contribute on this one, but I assume getting this to work with in-flight @BernieWhite requires some effort from your side so that these kind of resources are exported as well?

**Comment by BernieWhite** [comment]
@BenjaminEngeset Correct. I'll add a related issue.
