### ISSUE TITLE
Use a VM maintenance configuration for Arc enabled servers (preview)

### ISSUE THREAD

**Issue by BernieWhite** [Azure/PSRule.Rules.Azure#2122]
### Suggested rule

Arc enabled servers can be assigned a maintenance configuration which allows managed assessments and updates for VM patches within the guest operating system.

This can be done by creating a `Microsoft.Maintenance/configurationAssignments` sub resource with the linked maintenance configuration resource Id.

For in-flight resources we need to collect and export this data.

### Pillar

Operational Excellence

### Additional context

- https://learn.microsoft.com/azure/templates/microsoft.maintenance/configurationassignments
- https://learn.microsoft.com/azure/update-center/manage-arc-enabled-servers-programmatically
- https://learn.microsoft.com/azure/update-center/manage-update-settings

**Comment by BernieWhite** [comment]
@BenjaminEngeset Correct the parent resource is `Microsoft.HybridCompute/machines`.

**Comment by BenjaminEngeset** [comment]
Some interesting observations @BernieWhite when designing and creating the rule, I wonder if you have experienced the same. 

1. UMC uses an extension (relying on), this is installed and managed by an `Microsoft Azure Windows VM Agent`,
`Microsoft Azure Linux VM Agent` or ` Azure Connected Machine agent` depending on the platform. But I have no signs of any UMC extension installed by invoking the actions that should install it `(This extension is automatically installed when you initiate any update management center operations such as check for updates, install one time update, periodic assessment on your machine.)` It almost looks like a hidden resource block, it's not to be found in activity log or in the export template. Do you know if the UMC extension is visible somewhere, or what it's identifier is? I'm not able to find this information. The extension does not even look documented in the official extension repository. https://github.com/MicrosoftDocs/azure-docs/tree/main/articles/virtual-machines/extensions 

2. When creating an configuration assignment, it's visible in the activity log that it clearly creates a resource on the VM/machine scope, but it's not to be found in export template. But under the update blade on the VM/machine you can clearly see it's associated with the maintenance configuration. That really makes me wonder if this is some kind of hidden resource as well, and that we will not be able to make `in-flight` work for this.

Appreciate the feedback.

**Comment by BernieWhite** [comment]
@BenjaminEngeset I think the intent is that customer's should manage the update behaviour via `Microsoft.Maintenance/configurationAssignments`.

In it's raw form an extension is additional code that is run/ installed by the guest agent controlled through ARM.

You are correct that historically that has meant that there was a `/extensions` sub-resource used to control the deployment. However I guess the PG team felt that adding an additional `/extensions` sub-resource was not warranted, and the maintenance configuration is different enough.

Either way I don't see that as a problem, we should just look for the `Microsoft.Maintenance/configurationAssignments` sub-resource both pre-flight or in-flight.

---

Does that make sense?

**Comment by BenjaminEngeset** [comment]
> @BenjaminEngeset I think the intent is that customer's should manage the update behaviour via `Microsoft.Maintenance/configurationAssignments`.
> 
> In it's raw form an extension is additional code that is run/ installed by the guest agent controlled through ARM.
> 
> You are correct that historically that has meant that there was a `/extensions` sub-resource used to control the deployment. However I guess the PG team felt that adding an additional `/extensions` sub-resource was not warranted, and the maintenance configuration is different enough.
> 
> Either way I don't see that as a problem, we should just look for the `Microsoft.Maintenance/configurationAssignments` sub-resource both pre-flight or in-flight.
> 
> Does that make sense?

It does!

https://learn.microsoft.com/en-us/rest/api/maintenance/configuration-assignments/list?tabs=HTTP#configurationassignments_list Looks like it you can identify the parent machine by the resourceId so I guess it's all good.
