### ISSUE TITLE
Enable a defender profile for AKS clusters

### ISSUE THREAD

**Issue by BernieWhite** [Azure/PSRule.Rules.Azure#2123]
### Suggested rule

To collect and provide data plane protections of Microsoft Defender for Containers some additional daemon set and deployments needs to be deployed to the AKS clusters.

These components are installed when the defender profile is enabled on the cluster.

This can be enabled by setting the `properties.securityProfile.defender.securityMonitoring.enabled` to `true` (boolean).

### Pillar

Security

### Additional context

- https://learn.microsoft.com/azure/defender-for-cloud/defender-for-containers-enable?tabs=aks-deploy-arm%2Ck8s-deploy-asc%2Ck8s-verify-asc%2Ck8s-remove-arc%2Caks-removeprofile-api&pivots=defender-for-container-aks#use-azure-resource-manager-to-deploy-the-defender-profile
- https://learn.microsoft.com/azure/templates/microsoft.containerservice/managedclusters?pivots=deployment-language-bicep#managedclustersecurityprofiledefendersecuritymonitoring
- https://learn.microsoft.com/azure/defender-for-cloud/defender-for-containers-architecture

**Comment by BenjaminEngeset** [comment]
Any good recommendation naming this rule @BernieWhite?

**Comment by BernieWhite** [comment]
@BenjaminEngeset Lets go with `Azure.AKS.DefenderProfile`.
