### ISSUE TITLE
Check MDC Cloud Security Posture Management is using Standard plan

### ISSUE THREAD

**Issue by BernieWhite** [Azure/PSRule.Rules.Azure#2151]
### Suggested rule

Any pricing plans deployed for Microsoft Defender for Cloud should use the Standard pricing tier.

CSPM is now GA so there should be a rule similar to other workload protections.

### Pillar

Security

### Additional context

Same as #1632 but for Defender CSPM.

**Comment by BenjaminEngeset** [comment]
I'm already on it, so I'd like to contribute on this one.
