### ISSUE TITLE
Ignore Redis firewall rules for caches using private endpoints

### ISSUE THREAD

**Issue by BernieWhite** [Azure/PSRule.Rules.Azure#2171]
**Description of the issue**

The following rules are not applicable when Redis is configured to allow private connectivity by setting `properties.publicNetworkAccess` to `Disabled`.

- Azure.Redis.FirewallRuleCount
- Azure.Redis.FirewallRuleIPRange

We should update docs for these rules and add a precondition.

**Module in use and version:**

- Module: PSRule.Rules.Azure
- Version: **1.26.1**

**Additional context**

https://learn.microsoft.com/azure/azure-cache-for-redis/cache-network-isolation#limitations-of-firewall-rules

**Comment by BenjaminEngeset** [comment]
:shipit:
