### ISSUE TITLE
Enable AKS cluster autoscaler

### ISSUE THREAD

**Issue by BernieWhite** [Azure/PSRule.Rules.Azure#218]
# Rule request

## Suggested rule change

AKS clusters deployed with scale sets should enable the cluster autoscaler.

## Applies to the following

The rule applies to the following:

- Resource type: **Microsoft.ContainerService/managedClusters**

## Additional context

[Azure template reference](https://docs.microsoft.com/en-us/azure/templates/microsoft.containerservice/2019-08-01/managedclusters#managedclusteragentpoolprofile-object)

**Comment by ArmaanMcleod** [comment]
@BernieWhite I can help make a PR for this rule.

**Comment by BernieWhite** [comment]
@ArmaanMcleod Great thanks. Let me assign that to you. If you have any issues let me know.

**Comment by ArmaanMcleod** [comment]
@BernieWhite No worries. When creating the rule for the first time which ruleset to do you put it under?

I see the following baselines:

<img width="112" alt="baselines" src="https://user-images.githubusercontent.com/20082136/129159095-b952d24d-30e9-44e0-b498-638d05c6dff4.PNG">

**Comment by BernieWhite** [comment]
@ArmaanMcleod The ruleset references to the quarterly baseline they are release in. For new rules this is the next a quarterly baseline so the next baseline would be `2021_09`. Release `GA` and `preview` is determines by the Azure feature, so in this case AKS cluster autoscaler is a GA Azure features so it would be `GA`.

The quarterly baseline is designed to be a stable checkpoint for customers. So, if they are not ready to adopt new rules immediately, they can target a quarterly baseline and get a stable position even though we add rules each month.

At the end of the quarter, we cut a new baseline and deprecate the old one, which reports as a warning.

You don't need to worry about updating an old quarterly baseline. For `Azure.All.md` and `Azure.Default.md`, you can run the `Rule docs` task in VSCode and that should regenerate these files, ideally do this before you submit the PR.

**Comment by ArmaanMcleod** [comment]
@BernieWhite Thanks, added a `Azure.AKS.Autoscaling` rule in the PR. Should be ready for review.
