### ISSUE TITLE
Azure Container Apps may be prefered to be IP restricted

### ISSUE THREAD

**Issue by BenjaminEngeset** [Azure/PSRule.Rules.Azure#2189]
### Suggested rule

Azure Container Apps now supports restricting inbound traffic by IP addresses. 

This feature enables container apps to restrict inbound HTTP or TCP traffic by allowing or denying access to a specific list of IP address ranges.

This is general available.

In combination of the internal ingress type that we also recommend in `Azure.ContainerApp.ExternalIngress`, this will give customers the awareness of that fine-granulated network restrictions within an environment is now possible, or in just general use it with the external type to limit public and within the container app's internal environment traffic.

### Pillar

Security

### Additional context

https://learn.microsoft.com/nb-no/azure/container-apps/ingress-overview#ip-restrictions
https://learn.microsoft.com/en-us/azure/templates/microsoft.app/containerapps#ingress

**Comment by BernieWhite** [comment]
@BenjaminEngeset Great idea. If internal/ external ingress is enabled we should evaluate this rule.

The rule would check each `ipSecurityRestrictions` to make sure `action` is `allow`.

**Comment by BenjaminEngeset** [comment]
@BernieWhite Do you mind me using PowerShell here, or do we have the support in YAML for this?
