### ISSUE TITLE
Azure Container Apps may be prefered to restrict outbound traffic with UDRs 

### ISSUE THREAD

**Issue by BenjaminEngeset** [Azure/PSRule.Rules.Azure#2190]
### Suggested rule

Previously there has been no way of forcing egress traffic with User Defined Routes (UDR). This is now available in public preview for the Consumption + Dedicated plan structure.

It's a common pattern by WAF to recommend UDR to restrict outbound traffic with Azure Firewall e.g.

Only internal environments supports UDRs.

Create an UDR, associate the route table with the container app's subnet.

### Pillar

Security

### Additional context

https://learn.microsoft.com/azure/container-apps/networking#user-defined-routes-udr---preview

**Comment by BenjaminEngeset** [comment]
@BernieWhite Is this a rule we're even able to design, if so, how? I'm a bit struggled here how we can do it when we have to check the subnet has the UDR, but no way of finding the relationship with the environment's `infrastructureSubnetId`?

**Comment by BernieWhite** [comment]
@BenjaminEngeset Today, I don't think we could build this in a way that makes sense or provides a consistent result.

**Comment by BenjaminEngeset** [comment]
> provides

Thanks, agreed. Close it?

**Comment by BenjaminEngeset** [comment]
> @BenjaminEngeset Today, I don't think we could build this in a way that makes sense or provides a consistent result.

@BernieWhite Thanks, agreed. Close it?
