### ISSUE TITLE
Azure.MariaDB.Database failing when it shouldn't

### ISSUE THREAD

**Issue by Lucas-c-B** [Azure/PSRule.Rules.Azure#2191]
### Existing rule

Azure.MariaDB.DatabaseName

### Suggested rule

The rule is checking for the full name of the resource, which includes the parent. Because it includes the parent, it also includes the '/' seperator, causing the rule to fail.

### Pillar

None

**Comment by BernieWhite** [comment]
@Lucas-c-B Thanks for reporting the issue.
