### ISSUE TITLE
Microsoft Defender for Storage pricing plans should have sensitive data threat detection configured

### ISSUE THREAD

**Issue by BenjaminEngeset** [Azure/PSRule.Rules.Azure#2207]
### Suggested rule

Microsoft Defender for Storage introduces the sensitive data threat detection feature that can be configured within a pricing plan.

Sensitive data threat detection is powered by the sensitive data discovery engine, an agentless engine that uses a smart sampling method to find resources with sensitive data.

Currently this is a preview feature.

This can be enabled by configuring an extension under the subscription pricing plan or by a adding a standalone storage account to the pricing plan.

Example for subscription pricing plan: 

```
resource StorageAccounts 'Microsoft.Security/pricings@2023-01-01' = {
  name: 'StorageAccounts'
  properties: {
    pricingTier: 'Standard'
    subPlan: 'DefenderForStorageV2'
    extensions: [
      {
        name: 'SensitiveDataDiscovery'
        isEnabled: 'True'
      }
    ]
  }
}
```
Example for a specific storage account to the pricing plan:

```
resource storageAccount 'Microsoft.Storage/storageAccounts@2021-04-01' ...

resource defenderForStorageSettings 'Microsoft.Security/DefenderForStorageSettings@2022-12-01-preview' = {
  name: 'current'
  scope: storageAccount
  properties: {
    sensitiveDataDiscovery: {
      isEnabled: true
    }
    overrideSubscriptionLevelSettings: true
  }
}
```

### Pillar

Security

### Additional context

https://learn.microsoft.com/azure/defender-for-cloud/defender-for-storage-malware-scan
https://learn.microsoft.com/azure/storage/common/azure-defender-storage-configure

### Pillar

Security

### Additional context

https://learn.microsoft.com/azure/defender-for-cloud/defender-for-storage-data-sensitivity
https://learn.microsoft.com/azure/storage/common/azure-defender-storage-configure

**Comment by BernieWhite** [comment]
Same as #2206

This should be two rules.

The recommendation is to apply it at the subscription level, so the main rule should make sure it is turned on with the `Microsoft.Security/pricings` resource.

Then at the storage account level we should just check that that sensitive data discovery is not turned off via `Microsoft.Security/DefenderForStorageSettings`.
