### ISSUE TITLE
Storage accounts should have Microsoft Defender for Storage configured

### ISSUE THREAD

**Issue by BenjaminEngeset** [Azure/PSRule.Rules.Azure#2225]
### Suggested rule

Storage accounts should have Microsoft Defender for Storage configured.

Microsoft Defender for Storage provides additional security for storage accounts.

Protection is provided by:

- Continuously analyzing data and control plane logs from protected storage accounts.
- Malicious scanning by performing a full malware scan on uploaded content in near real time, leveraging Microsoft Defender Antivirus capabilities.
- Sensitive data threat detection by a smart sampling method to find resources with sensitive data.

A plan can be enabled at resource level by configuring a `Microsoft.Security/DefenderForStorageSettings` sub-resource.

We should check that storage accounts has Microsoft Defender for Storage configured as in enabled. 

Related to #2206
Related to #2207

### Pillar

Security

### Additional context

https://learn.microsoft.com/azure/defender-for-cloud/defender-for-storage-introduction
https://learn.microsoft.com/azure/storage/common/azure-defender-storage-configure

**Comment by BenjaminEngeset** [comment]
Hi @BernieWhite. What kind of logic would you recommend here? Configuration option and keep the subscription level as the main for customers? Like we did on Cosmos DB. Consequence by doing so is that customers will not be aware the importanance of this for storage accounts if they don't deal with subscription plans, but since it should be closest to WAF the subscription level is the general recommendation.

**Comment by BernieWhite** [comment]
@BenjaminEngeset agreed. Subscription method is recommended, so we don't want to require this unless it is specific to their environment. Otherwise customers need to add additional configuration for no benefit to pass the tests only.

**Comment by BernieWhite** [comment]
@BenjaminEngeset I'll have a think about how we can make these rules clearer in the documentation. However no change to the plan is required at this stage.
