### ISSUE TITLE
[Bug] Azure.APIM.ManagedIdentity when SystemAssigned and UserAssigned Identities are enabled

### ISSUE THREAD

**Issue by ayoussef-insight** [Azure/PSRule.Rules.Azure#2235]
### Existing rule

Azure.APIM.ManagedIdentity

### Suggested rule

Azure.APIM.ManagedIdentity rule fails with the following error when both UserAssigned and SystemAssigned Managed identities are enabled on the resource.

Recommend:
  Consider configuring a managed identity for each API Management instance. Also
  consider using managed identities to authenticate to related Azure services.

  Reason:
  - Path Identity.Type: The value 'SystemAssigned,UserAssigned' was not in 'System.String[]'.

### Pillar

Security

**Comment by BernieWhite** [comment]
@ayoussef-insight Thanks for reporting the issue.

**Comment by ayoussef-insight** [comment]
Thanks @BernieWhite for the quick fix
