### ISSUE TITLE
Redis Firewall rules: Cannot bind argument to parameter 'Start' because it is an empty string

### ISSUE THREAD

**Issue by omar-oropeza** [Azure/PSRule.Rules.Azure#2303]
Azure.Redis.FirewallRuleCount and Azure.Redis.FirewallIPRange failed with the message:

failed Azure.Redis.FirewallRuleCount with the error 'Cannot bind argument to parameter 'Start' because it is an empty string

failed Azure.Redis.FirewallIPRange with the error 'Cannot bind argument to parameter 'Start' because it is an empty string

the properties for the Redis firewall is called startIp and endIp, the code is looking for startIpAddress and endIpAddress which is incorrect for the redis firewall schema: https://learn.microsoft.com/en-us/azure/templates/microsoft.cache/2020-12-01/redis/firewallrules?pivots=deployment-language-bicep#resource-format

https://github.com/Azure/PSRule.Rules.Azure/blob/b50550a5ddc31462a07fc997b4a9270be1a20d59/src/PSRule.Rules.Azure/rules/Azure.Common.Rule.ps1#L433C28-L433C46

**Comment by BernieWhite** [comment]
@omar-oropeza Thanks for reporting the issue. You are correct.
