### ISSUE TITLE
Azure.MariaDB.VNETRuleName and Azure.MariaDB.FirewallRuleName failing when they shouldn't

### ISSUE THREAD

**Issue by Lucas-c-B** [Azure/PSRule.Rules.Azure#2335]
Existing rule
Azure.MariaDB.VNETRuleName
Azure.MariaDB.FirewallRuleName

Suggested rule
The rules are checking for the full name of the resource, which includes the parent. Because it includes the parent, it also includes the '/' seperator, causing the rules to fail.

Pillar
None

Additional context
No response

**Comment by BernieWhite** [comment]
Thanks for reporting the issue @Lucas-c-B
