### ISSUE TITLE
Firewall policy threatIntelMode  should use deny

### ISSUE THREAD

**Issue by BernieWhite** [Azure/PSRule.Rules.Azure#2354]
### Suggested rule

Added rule for Azure Firewall policy for base policy to use `threatIntelMode` set to `deny`.

Ignore non base policies except if the non-base policy explicitly sets the `threatIntelMode`.

### Pillar

Security

**Comment by BenjaminEngeset** [comment]
Hi @BernieWhite, I'd like to give this a try.

As a start:

I can tell that the firewall can have this directly configured by https://learn.microsoft.com/en-us/azure/templates/microsoft.network/firewallpolicies?pivots=deployment-language-bicep#firewallpolicypropertiesformat, but I'm not sure if that creates a fundamental base policy with that only, or if it adds it on the associated base policy if specified together with https://learn.microsoft.com/en-us/azure/templates/microsoft.network/firewallpolicies?pivots=deployment-language-bicep#subresource only.

Or should we only focus on the `Microsoft.Network/firewallPolicies` resource type?

To me it looks like this can be configured for both resource types, but I'm not sure.

**Comment by BernieWhite** [comment]
Hi @BenjaminEngeset, `threatIntelMode` can be set in Azure Firewall (`Microsoft.Network/azureFirewalls`) referred to as classic policies and Azure Firewall Policies (`Microsoft.Network/firewallPolicies`).

The suggest approach is to use Azure Firewall Policies.

When using Azure Firewall Policies they can be inherited by chaining multiple policies together although this isn't required and it's always applicable.

i.e.

- Base policy
  - Policy 1
  - Policy 2

A policy is inherited from another policy by setting `properties.basePolicy.id`.

The intent of this rule is to only apply to `Microsoft.Network/firewallPolicies` and base policy that do not have `properties.basePolicy.id` set.

---

For a base policy the `properties.threatIntelMode` should be set to `deny`.

There is already a rule for classic managed rules called `Azure.Firewall.Mode` so let call this rule `Azure.Firewall.PolicyMode`.
