### ISSUE TITLE
I have issue with 'contains' function array logic.

### ISSUE THREAD

**Issue by Rycardas** [Azure/PSRule.Rules.Azure#2368]
Hello, I have exact same issue as described [here](https://github.com/Azure/PSRule.Rules.Azure/issues/1793) 
While using same [code ](https://gist.github.com/s1mb414/a40b922d2e37279207061b7680a3ecdb) to evaluate individual resourses price tier.
While evaluating, contains function returns "false" (Free tier) instead of expected "true" (Standard). 

Modules i have:
1.28.2               PSRule.Rules.Azure 
2.9.0                PSRule

Please see a screenshot with few error messages. 
![image](https://github.com/Azure/PSRule.Rules.Azure/assets/55191252/5ca7f4f5-87c9-4190-b8b5-308e482b8adb)

_Originally posted by @Rycardas in https://github.com/Azure/PSRule.Rules.Azure/issues/1793#issuecomment-1662174330_

**Comment by BernieWhite** [comment]
@Rycardas Thanks for reporting the issue.
