### ISSUE TITLE
[Azure.VNET.LocalDNS] False positive for DNS server addresses out of local scope.

### ISSUE THREAD

**Issue by grzsar** [Azure/PSRule.Rules.Azure#2370]
### Existing rule

Azure.VNET.LocalDNS

### Suggested rule

Hello,
Current rule code checks if `properties.dhcpOptions.dnsServers` attribute is set for VNET and if:
`# Primary DNS server must be within VNET address space or peered VNET`.
Second condition can't not be fulfilled for some correct landing zone architectures, like Enterprise-scale architecture with AD Domain controllers as DNS servers. This type of deployment we can see on nice picture on [Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/) website. DNS servers (AD domain controllers) are in separate subscription - "Identity Subscription" and their addresses are nether in landing zones VNETs nor peered. 
Current condition about "local" address result false positives for correct settings. I kindly ask to remove second condition which check if address is in scope or provide other solution to solve false positives.
![CAF Enterprise-scale architecture](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/enterprise-scale/media/ns-arch-cust-expanded.svg)

### Pillar

None

**Comment by BernieWhite** [comment]
Hi @grzsar thanks for your feedback.

In the meantime, you can exclude or suppress the rule if it doesn't apply to your environment. https://azure.github.io/PSRule.Rules.Azure/concepts/suppression/#excluding-a-rule

**Comment by BernieWhite** [comment]
@grzsar Would a configuration option to flag you are using an identity subscription for DNS be an acceptable option?

**Comment by grzsar** [comment]
@BernieWhite Yes, I think so.
