### ISSUE TITLE
Container registry should only accept explicitly allowed traffic

### ISSUE THREAD

**Issue by BernieWhite** [Azure/PSRule.Rules.Azure#2423]
### Suggested rule

Create a new rule `Azure.ACR.Firewall`.

This rule should fail if the network access is not restricted.

This rule should pass if:

-  `properties.publicNetworkAccess` is set to `Disabled` OR
- `properties.networkRuleSet.defaultAction` is set to `Deny`

Configuring firewall rules or using private endpoints is only available on Premium container registries. So this rule only applies to the Premium SKU.

### Pillar

Security

### Additional context

- https://learn.microsoft.com/en-us/azure/well-architected/security/design-network-endpoints
- https://learn.microsoft.com/en-us/azure/templates/microsoft.containerregistry/registries?pivots=deployment-language-bicep

When used with Microsoft Defender for Containers, you must enable trusted Microsoft services for the vulnerability assessment feature to be able to scan the registry.

- https://learn.microsoft.com/en-us/azure/defender-for-cloud/agentless-container-registry-vulnerability-assessment
- https://learn.microsoft.com/en-us/azure/container-registry/allow-access-trusted-services#trusted-services

**Comment by BenjaminEngeset** [comment]
Great. :shipit:
