### ISSUE TITLE
WAF Alignments of rules - wave 1

### ISSUE THREAD

**Issue by BernieWhite** [Azure/PSRule.Rules.Azure#2493]
### Suggested rule

Azure Verified Modules has identified rules that possibly don't have clear WAF linkage. Since PSRule for Azure is WAF aligned we want the default rule sets to only include WAF aligned rules.

Other related discussion: Azure/Azure-Verified-Modules#349

So, any non-WAF rules should be handled by:

1. Make them opt-in only, and not run by default. OR
2. Update and link them to WAF.

### Pillar

None

### Additional context

Azure Verified Modules has identified rules that don't have clear WAF linkage. Since PSRule for Azure is WAF aligned we want the default rule sets to only include WAF aligned rules.

So, any non-WAF rules should be handled by:

1. Make them opt-in only, and not run by default. OR
2. Update and link them to WAF.

---

## Review

- [x] https://azure.github.io/PSRule.Rules.Azure/en/rules/Azure.Template.UseVariables/
- [x] https://azure.github.io/PSRule.Rules.Azure/en/rules/Azure.Template.UseParameters/
- [x] https://azure.github.io/PSRule.Rules.Azure/en/rules/Azure.Template.ResourceLocation/
- [x] https://azure.github.io/PSRule.Rules.Azure/en/rules/Azure.Template.DefineParameters/
- [x] https://azure.github.io/PSRule.Rules.Azure/en/rules/Azure.Template.ValidSecretRef/

**Comment by rahalan** [comment]
adding https://azure.github.io/PSRule.Rules.Azure/en/rules/Azure.VM.UseHybridUseBenefit/
