### ISSUE TITLE
[BUG] Azure.ServiceBus.AuditLogs - False failure during deployment

### ISSUE THREAD

**Issue by ChrisSidebotham** [Azure/PSRule.Rules.Azure#2564]
### Existing rule

Azure.ServiceBus.AuditLogs

### Description of the issue

Rule is not picking up configured diagnostic settings for Premium SKU Service Bus I have checked by applying all variations of accepted logging, this is for AVM module development:

- RuntimeAuditLogs category.
- audit category group.
- allLogs category group.

Bicep to deploy:
```bicep 
resource serviceBusNamespace_diagnosticSettings 'Microsoft.Insights/diagnosticSettings@2021-05-01-preview' = [for (diagnosticSetting, index) in (diagnosticSettings ?? []): {
  name: diagnosticSetting.?name ?? '${name}-diagnosticSettings'
  properties: {
    storageAccountId: diagnosticSetting.?storageAccountResourceId
    workspaceId: diagnosticSetting.?workspaceResourceId
    eventHubAuthorizationRuleId: diagnosticSetting.?eventHubAuthorizationRuleResourceId
    eventHubName: diagnosticSetting.?eventHubName
    metrics: diagnosticSetting.?metricCategories ?? [
      {
        category: 'AllMetrics'
        timeGrain: null
        enabled: true
      }
    ]
    logs: diagnosticSetting.?logCategoriesAndGroups ?? [
      {
        categoryGroup: 'AllLogs'
        enabled: true
      }
    ]
    marketplacePartnerId: diagnosticSetting.?marketplacePartnerResourceId
    logAnalyticsDestinationType: diagnosticSetting.?logAnalyticsDestinationType
  }
  scope: serviceBusNamespace
}]
```

Result in Resource (Azure):
![image](https://github.com/Azure/PSRule.Rules.Azure/assets/48600046/7f0edc11-3d7c-4ca3-b472-fb7524efbd5b)

Configured settings:
![image](https://github.com/Azure/PSRule.Rules.Azure/assets/48600046/c7b803bf-8089-4a47-8538-831f4861d9f8)

### Error messages

    [FAIL] Azure.ServiceBus.AuditLogs (AZR-000358)
    | Template: avm/res/service-bus/namespace/tests/e2e/waf-aligned/main.test.bicep:1259:36

    | RECOMMEND:
    | Consider configuring diagnostic settings to record interactions with data of
    | the Service Bus.

    | REASON:
    | - Minimum one diagnostic setting should have (RuntimeAuditLogs) configured or category group (audit, allLogs) configured.

    | HELP:
    | - https://azure.github.io/PSRule.Rules.Azure/en/rules/Azure.ServiceBus.AuditLogs/

Error: AZR-000358: ***sbnwaf001 failed Azure.ServiceBus.AuditLogs. Ensure namespaces audit diagnostic logs are enabled.

### Reproduction

See AVM Module located here: https://github.com/ChrisSidebotham/bicep-registry-modules/blob/avm-res-servicebus-namespace/avm/res/service-bus/namespace/tests/e2e/waf-aligned/main.test.bicep

### Version of PSRule

2.9.0

### Version of PSRule for Azure

1.31.3

**Comment by BernieWhite** [comment]
@ChrisSidebotham Thanks for reporting the issue.
