### ISSUE TITLE
[BUG] Failure to expand copy loop in a Azure Policy deployment

### ISSUE THREAD

**Issue by JonasCordsen** [Azure/PSRule.Rules.Azure#2605]
### Existing rule

Azure,CAF

### Description of the issue

I am trying to deploy all ALZ policies, and have them protected by PSrule to ensure they are setup as expected.
I do, however get an error for one policy that uses Copy inside the setup.

[azureDeploy.parameters.json](https://github.com/Azure/PSRule.Rules.Azure/files/13657541/azureDeploy.parameters.json)
[azureDeploy.json](https://github.com/Azure/PSRule.Rules.Azure/files/13657540/azureDeploy.json)

### Error messages

   ERROR  Unable to expand resources because the template /.policy/.definitions/ALZDeploy-Custom-Route-Table/azureDeploy.json' was not valid with parameters '/.policy/.definitions/ALZDeploy-Custom-Route-Table/azureDeploy.parameters.json'. Invalid cast from 'System.String' to 'Newtonsoft.Json.Linq.JArray'.

### Reproduction

Running:
$splat = @{
    InputPath = "/.policy/.definitions/ALZDeploy-Custom-Route-Table/azureDeploy.parameters.json"
    Option = $optionsFile.FullName
    Path = $rulesFolder.FullName
}
Assert-PSRule @splat -Outcome Error,Fail

### Version of PSRule

2.9.0

### Version of PSRule for Azure

1.30.3

**Comment by BernieWhite** [comment]
Thanks for reporting the issue @JonasCordsen.
