### ISSUE TITLE
[RULE] Update Azure.AppGwWAF.RuleGroups to use the latest bot manager rule set

### ISSUE THREAD

**Issue by BenjaminEngeset** [Azure/PSRule.Rules.Azure#2629]
### Existing rule

Azure.AppGwWAF.RuleGroups

### Suggested rule

The rule `Azure.AppGwWAF.RuleGroups` currently has the following definition:

https://github.com/Azure/PSRule.Rules.Azure/blob/21cb4782286585d827c989bf8c0cdc4178526a7d/src/PSRule.Rules.Azure/rules/Azure.AppGwWAF.Rule.yaml#L99-L100

This leads to  the `1.0` value to fail as `1.0` is a newer major version.

We should update the rule to use the latest bot manager rule set `1.0` instead. The updated rule set also introduces further enhancements over the older `0.1` version.

### Pillar

Security

### Additional context

https://azure.microsoft.com/en-us/updates/general-availability-bot-manager-rule-set-10-on-regional-azure-web-application-firewall/

**Comment by BernieWhite** [comment]
@BenjaminEngeset Thanks for reporting the issue. Good call out.
