### ISSUE TITLE
[RULE] Event Hub Firewall

### ISSUE THREAD

**Issue by BernieWhite** [Azure/PSRule.Rules.Azure#2701]
### Suggested rule

Access to Event Hub endpoints should be restricted to only allowed sources.

- Ideally use private endpoints. OR
- Configure the firewall in default `deny` mode.

### Pillar

Security

### Additional context

- https://learn.microsoft.com/en-us/azure/event-hubs/event-hubs-ip-filtering
- https://learn.microsoft.com/en-us/azure/event-hubs/private-link-service
- https://learn.microsoft.com/en-us/azure/event-hubs/policy-reference
- https://learn.microsoft.com/en-us/security/benchmark/azure/baselines/event-hubs-security-baseline?toc=%2Fazure%2Fevent-hubs%2FTOC.json#disable-public-network-access

**Comment by BenjaminEngeset** [comment]
:shipit:
