### ISSUE TITLE
[RULE] Disable cosmos account public access

### ISSUE THREAD

**Issue by BernieWhite** [Azure/PSRule.Rules.Azure#2702]
### Suggested rule

Cosmos DB accounts should not be exposed as public endpoints. Use the service firewall to only permit private network access to the account.

### Pillar

Security

### Additional context

- https://learn.microsoft.com/en-us/azure/cosmos-db/how-to-configure-private-endpoints?tabs=arm-bicep
- https://learn.microsoft.com/en-us/azure/templates/microsoft.documentdb/databaseaccounts?pivots=deployment-language-bicep

**Comment by BenjaminEngeset** [comment]
:shipit:
