### ISSUE TITLE
AKS clusters using Azure CNI should use large subnets

### ISSUE THREAD

**Issue by BernieWhite** [Azure/PSRule.Rules.Azure#273]
# Rule request

## Suggested rule change

Production AKS clusters should be deployed to a subnet of a minimum size to reduce IP exhaustion issues.
Subnet should be at least **/23**.

## Applies to the following

The rule applies to the following:

- Resource type: **Microsoft.ContainerService/managedClusters**

**Comment by ArmaanMcleod** [comment]
@BernieWhite I'd be happy to take this one on. Should be similar to the work I did before 😄.

**Comment by BernieWhite** [comment]
@ArmaanMcleod Great Armaan. Reach out if you have any questions.

**Comment by ArmaanMcleod** [comment]
Thanks @BernieWhite. I guess I'll need to figure out how to get the subnet range, given only `vnetSubnetID` is exposed in the template. Will probably need to query this information in a separate function. 

Do you know where I could create such a function, which will be exposed to the rule as well? I see a lot of functions in `PSRule.Rules.Azure.psml` that use Azure PowerShell, would this be the best place for it?

For testing, I could probably mock these functions to give set subnet range using Pester. 

What do you think?

**Comment by BernieWhite** [comment]
@ArmaanMcleod Yes currently there wouldn't be a reliable way to get the size of the subnet from within a template. Querying a REST API isn't going to work if the VNET/ subnet is not yet deployed. I would suggest that this rule wouldn't be applicable to templates.

The subnet associated to a node pool is already added as a nested resource [here](https://github.com/Azure/PSRule.Rules.Azure/blob/main/src/PSRule.Rules.Azure/PSRule.Rules.Azure.psm1#L884-L902).

Would apply when you run `Export-AzRuleData` to dump a runtime configuration from Azure.

Previously, if used the `-If { IsExport }` as a rule pre-condition. See an examle of [Azure.ACR.Usage](https://github.com/Azure/PSRule.Rules.Azure/blob/main/src/PSRule.Rules.Azure/rules/Azure.ACR.Rule.ps1#L46).

**Comment by ArmaanMcleod** [comment]
@BernieWhite Ah that makes sense. Yeah limiting this rule to `Export-AzRule` sounds like a much better idea. I also considered the case where a subnet doesn't exist, but limiting it to just exports should solve this.

I'll let you know how I go, cheers for help mate 🙂.
