### ISSUE TITLE
[BUG] Error: PSR0004: The specified Baseline resource 'Azure.Pillar.Reliability' is not known.

### ISSUE THREAD

**Issue by jtracey93** [Azure/PSRule.Rules.Azure#2752]
### Description of the issue

Trying to use the `Azure.Pillar.Reliability` baseline, as per https://azure.github.io/PSRule.Rules.Azure/working-with-baselines/#pillar-specific-baselines, but getting the below error when using in GitHub Actions:

`Error: PSR0004: The specified Baseline resource 'Azure.Pillar.Reliability' is not known.` (a link to the GitHub Action workflow run can be found here: https://github.com/jtracey93/bicep-registry-modules/actions/runs/8256586807/job/22585554510#step:4:210)

![image](https://github.com/Azure/PSRule.Rules.Azure/assets/41163455/20b8fe4a-0eb5-46bd-b005-863ad5e629b6)

### Error messages

`Error: PSR0004: The specified Baseline resource 'Azure.Pillar.Reliability' is not known.`

### Reproduction

Try and use the `Azure.Pillar.Reliability` baseline in GitHub actions

### Version of PSRule

2.9.0

### Version of PSRule for Azure

1.34.2

### Additional context

Link to GitHub action step - https://github.com/jtracey93/bicep-registry-modules/blob/771baef304feea414422ec4487a7f1077c6e1372/.github/actions/templates/avm-validateModulePSRule/action.yml#L130-L142

Happy to explain over a call

**Comment by BernieWhite** [comment]
@jtracey93 We haven't shipped this feature yet, it's in v1.35.0. A preview release will ship ~end of week. I'll update the docs to reflect this.
