### ISSUE TITLE
[ERROR] Failed to expand bicep source: Cannot process argument because the value of argument "name" is not valid.

### ISSUE THREAD

**Issue by maythamfahmi** [Azure/PSRule.Rules.Azure#2850]
### Existing rule

Azure.AppService

### Description of the issue

I have following userAssignedIdentities for Web app

```
identity: {
    type: 'UserAssigned'
    userAssignedIdentities: {
      '${userAssignedScope}': {}
    }
  }
```
  It works fine when I deploy it. But when I run PSRule, it fails with following error
  
[ERROR] Failed to expand bicep source '\Infrastructure\infra\main.dev-nb.bicepparam'. Exception calling "GetBicepParamResources" with "2" argument(s): "Cannot process argument because the value of argument "name" is not valid. Change the value of the "name" argument and run the operation again."
    [ERROR] Failed to expand bicep source '\Infrastructure\infra\main.dev.bicepparam'. Exception calling "GetBicepParamResources" with "2" argument(s): "Cannot process argument because the value of argument "name" is not valid. Change the value of the "name" argument and run the operation again."
    
 
![image](https://github.com/Azure/PSRule.Rules.Azure/assets/9260645/f5e92b20-a613-4b43-bf32-a6844ea90314)

### Error messages

    [ERROR] Failed to expand bicep source '\Infrastructure\infra\main.dev.bicepparam'. Exception calling "GetBicepParamResources" with "2" argument(s): "Cannot process argument because the value of argument "name" is not valid. Change the value of the "name" argument and run the operation again."

### Reproduction

```
identity: {
    type: 'UserAssigned'
    userAssignedIdentities: {
      '${userAssignedScope}': {}
    }
  }
```
  
gives the error when disabling 
  
```
  identity: {
    type: 'UserAssigned'
    //userAssignedIdentities: {
    //  '${userAssignedScope}': {}
    //}
  }
```
  
PSRule Test works

But need to enable it again for deployment.

### Version of PSRule

2.9.0

### Version of PSRule for Azure

1.36.0

### Additional context

When searching, I found this #2751 but it did not make me wiser.

**Comment by BernieWhite** [comment]
@maythamfahmi Thanks for reporting the error.

Are you able to provide a little more detail around `userAssignedScope`?

- Is this a variable or parameter in a `.bicep` file?
- If it is a parameter, is it set by an output from another module?
- Can provide an example of where it is defined and where is it set?

**Comment by maythamfahmi** [comment]
> @maythamfahmi Thanks for reporting the error.
> 
> Are you able to provide a little more detail around `userAssignedScope`?
> 
> * Is this a variable or parameter in a `.bicep` file?
> * If it is a parameter, is it set by an output from another module?
> * Can provide an example of where it is defined and where is it set?

Thanks, I am glad for your quick feedback, here is my answer:
parameter in appService.bicep that takes the value from an output. As mentioned it deploys fine in Azure and works as expected, it is more psrule that comes with this error message.


appService.bicep
```
param location string
param appServicePlanName string
param webAppName string
param userAssignedScope string

resource asp 'Microsoft.Web/serverfarms@2023-01-01' = {
  name: appServicePlanName
  location: location
  sku: {
    name: 'S1'
  }
}

resource webApp 'Microsoft.Web/sites@2023-01-01' = {
  name: webAppName
  location: location
  identity: {
    type: 'UserAssigned'
    userAssignedIdentities: {
      '${userAssignedScope}': {}
    }
  }
  properties: {
    serverFarmId: asp.id
    httpsOnly: true
  }
}
```

main.bicep
```
module appService '../modules/appService/appService.bicep' = {
  name: 'WebApp-Deployment'
  scope: resourceGroup(rgAppService.name)
  params: {
    webAppName: '${appServiceName}'
    appServicePlanName: '${appServicePlanName}'
    location: location
    skuName: webAppSkuName
    userAssignedScope: userAssignedId.outputs.scope
  }
}
```

**Comment by BernieWhite** [comment]
@maythamfahmi Ok thanks for the additional detail.

Some follow up questions.

- What is `scope` set from?
  - Is it the resource `id` of a user-assigned managed identity or something different?

In the common case it would be something like, because the resource `id` is required for the `userAssignedIdentities` block:

```bicep

// ---------
// RESOURCES
// ---------

@sys.description('Create or update a User-Assigned Managed Identity.')
resource identity 'Microsoft.ManagedIdentity/userAssignedIdentities@2023-01-31' = {
  name: name
  location: location
}

// -------
// OUTPUTS
// -------

@sys.description('A unique identifier for the Managed Identity.')
output id string = identity.id
```

**Comment by maythamfahmi** [comment]
yes, I use `output scope string = userAssignedIdentities.id`, the same as `output id string = identity.id`

**Comment by maythamfahmi** [comment]
@BernieWhite I have made a little found that might enlighten your debugging work. I did a review with my colleague Jonas, and he suggested for fun trying to harden the id. Funny enough the PSRule works fine. With that said.

So when testing with this it works:

userAssignedIdentities: {
      '/subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/rg-name/providers/Microsoft.ManagedIdentity/userAssignedIdentities/id-name': {}
    }

**Comment by BernieWhite** [comment]
@maythamfahmi The issue is cause by the resource IDs for the module deployments being incorrectly generated when you have a subscription level target scope and modules targeted to a resource group scope.

---

A fix will be available in the next pre-release, available in the next few days. As a workaround:

- Order the modules in the parent deployment is required order. i.e. in this case define the managed identity before the app service. OR
- Using an `exsiting` reference or `resourceId` function or concat the resource ID (less preferred) in the app service module.

**Comment by maythamfahmi** [comment]
@BernieWhite just to let you know, the same issue is happening for `Microsoft.Cdn/profiles@2024-02-01`

**Comment by BernieWhite** [comment]
@maythamfahmi OK, thanks. This is also for v1.36.0 or are you trying with a v1.37.0 preview?

**Comment by maythamfahmi** [comment]
@BernieWhite  😊I still using 1.36.0, I will try with 1.37.0 preview and let you know

**Comment by nbwdk** [comment]
@BernieWhite 

We are still seeing this issue, when passing UserAssignedIdentity properties, between bicep modules.

`   ERROR  Failed to expand bicep source '/main.test.bicepparam'. Exception calling "GetBicepParamResources" with "2" argument(s): "Unable to expand resources because the source file '/main.test.bicepparam' was not valid. An error occurred evaluating expression '[reference('userAssignedIdentity').outputs.id.value]' line 1414. The language expression property 'id' doesn't exist."`

Using PSRule version 1.39.2

containerRegistry.bicep
```
targetScope = 'resourceGroup'

param containerRegistryName string
@allowed([
  'Basic'
  'Standard'
  'Premium'
])
param containerRegistrySku string
param location string
param logAnalyticsId string
param userAssignedId string
param acrRoleAssignments object[]
param tags object

resource containerRegistry 'Microsoft.ContainerRegistry/registries@2023-11-01-preview' = {
  name: containerRegistryName
  location: location
  identity: {
    type: 'UserAssigned'
    userAssignedIdentities: {
      '${userAssignedId}': {}
    }
  }
  sku: {
    name: containerRegistrySku
  }
  tags:tags
  properties: {
    adminUserEnabled: false
    policies: {
      azureADAuthenticationAsArmPolicy: {
        status: 'enabled'
      }
    }
  }
}

resource acrMonitoring 'Microsoft.Insights/diagnosticSettings@2021-05-01-preview' = {
  name: '${containerRegistryName}-logging'
  scope: containerRegistry
  properties: {
    logs: [
      {
        category: 'ContainerRegistryRepositoryEvents'
        enabled: true
      }
      {
        category: 'ContainerRegistryLoginEvents'
        enabled: true
      }
    ]
    metrics: [
      {
        category: 'AllMetrics'
        enabled: true
      }
    ]
    workspaceId: logAnalyticsId
  }
}

@description('Following will add principals to the key vault Reader')
module acrReaderRoleAssignment 'rgRoleAssignment.bicep' = {

  name: 'acrReaderRoleAssignment'
  params: {
 roleAssignments:acrRoleAssignments
  }
}

output containerRegistryName string = containerRegistry.name
output containerRegistryId string = containerRegistry.id
output containerRegistryUrl string = containerRegistry.properties.loginServer

```

Common.bicep
```
targetScope = 'subscription'
// Parameters
@description('')
@allowed([
  'test'
  'prod'
])
@minLength(3)
@maxLength(4)
param environment string

@description('')
@maxLength(3)
param solutionName string

@description('')
@maxLength(5)
param companyInitName string

@description('Deployment Location')
@allowed([
  'westeurope'
  'northeurope'
  'swedencentral'
])
param location string

@description('')
param sequenceNo string
@description('')
param tags object
@description('')
param persistent bool
@description('')
param commonSubnetId string
@description('')
param clusterSubnetId string
@description('')
param logAnalyticsWorkspaceId string
@description('')
param kvRoleAssignments object[]
@description('')
param acrRoleAssignments object[]
@description('')
param appInsightsName string
@description('')
param appiConnectionString string

//Function import
import { naming } from '../../functions/naming.bicep'

// Variables
var sequence = environment == 'prod' ? '' : '${sequenceNo}'
var rgCommonName = naming('rg', 'common', companyInitName, solutionName, environment, sequence).name
var keyVaultName = naming('kv', '', companyInitName, solutionName, environment, sequence).name
var userAssignedIdentityName = naming('id', '', companyInitName, solutionName, environment, sequence).name
var containerRegistryName = naming('acr', '', companyInitName, solutionName, environment, sequence).nameWithoutDash

// Resources

resource rgCommon 'Microsoft.Resources/resourceGroups@2024-07-01' = {
  name: rgCommonName
  location: location
  tags: union(tags, {})
}

module rgCommonPersistentLock '../../core/lockRg.bicep' = if (persistent) {
  name: '${rgCommonName}-Lock-Deployment'
  scope: rgCommon
}

module userAssignedIdentity '../../core/userAssignedIdentities.bicep' = {
  scope: rgCommon
  name: '${userAssignedIdentityName}-Deployment'
  params: {
    userAssignedName: userAssignedIdentityName
    location: location
    tags: tags
  }
}

var kvRoleAssignmentsAutoGenerated = [
  {
    name: 'Key Vault Secrets User: Allow web app Reader role to key vault via User Assigned Identity'
    roleDefinitionResourceId: '/providers/Microsoft.Authorization/roleDefinitions/4633458b-17de-408a-b874-0445c86b69e6'
    principalId: userAssignedIdentity.outputs.principalObjectId
    principalType: 'ServicePrincipal'
  }
]

module keyVault '../../core/keyVault.bicep' = {
  name: '${keyVaultName}-Deployment'
  scope: rgCommon
  params: {
    subnetIds: [
      {
        id: commonSubnetId
      }
      {
        id: clusterSubnetId
      }
    ]
    keyVaultName: keyVaultName
    location: location
    tags: tags
    logAnalyticsWorkspaceId: logAnalyticsWorkspaceId
    kvRoleAssignments: union(kvRoleAssignments, kvRoleAssignmentsAutoGenerated)
  }
  dependsOn: [
    userAssignedIdentity
  ]
}

var acrRoleAssignmentsAutoGenerated = [
  {
    name: 'AcrPull. Pull artifacts from a container registry.'
    roleDefinitionResourceId: '/providers/Microsoft.Authorization/roleDefinitions/7f951dda-4ed3-4680-a7ca-43fe172d538d'
    principalId: userAssignedIdentity.outputs.principalObjectId
    principalType: 'ServicePrincipal'
  }
]

module containerRegistry '../../core/containerRegistry.bicep' = {
  scope: rgCommon
  name: '${containerRegistryName}-Deployment'
  params: {
    location: location
    acrRoleAssignments: union(acrRoleAssignments, acrRoleAssignmentsAutoGenerated)
    containerRegistryName: containerRegistryName
    containerRegistrySku: 'Standard'
    logAnalyticsId: logAnalyticsWorkspaceId
    tags: tags
    userAssignedId: userAssignedIdentity.outputs.id
  }
  dependsOn: [
    userAssignedIdentity
  ]
}

module applicationInsightsConnectionString '../../core/keyVaultCreateSecret.bicep' = {
  name: '${appInsightsName}-Secret-Deployment'
  scope: rgCommon
  params: {
    keyVaultName: keyVaultName
    secretName: '${appInsightsName}ConnectionString'
    secretValue: appiConnectionString
  }
  dependsOn: [
    keyVault
  ]
}

@description('User Assigned Identity Id (scope)')
output userAssignedIdentityId string = userAssignedIdentity.outputs.id
@description('User Assigned Identity Principle Id (Object Id)')
output userAssignedIdentityObjectId string = userAssignedIdentity.outputs.principalObjectId
@description('User Assigned Identity Client Id')
output userAssignedIdentityClientId string = userAssignedIdentity.outputs.clientId
output containerRegistryName string = containerRegistry.outputs.containerRegistryName
output containerRegistryId string = containerRegistry.outputs.containerRegistryId
output containerRegistryUrl string = containerRegistry.outputs.containerRegistryUrl
output keyVaultName string = keyVault.outputs.keyVaultName

```
