### ISSUE TITLE
Enable MySQL Advanced Threat Protection

### ISSUE THREAD

**Issue by BernieWhite** [Azure/PSRule.Rules.Azure#287]
# Rule request

## Suggested rule change

Use Advanced Threat Protection for Azure Database for MySQL server.

## Applies to the following

The rule applies to the following:

- Resource type: **Microsoft.DBforMySQL/servers**

## Additional context

- [Azure resource template](https://docs.microsoft.com/en-us/azure/templates/microsoft.dbformysql/2017-12-01/servers/securityalertpolicies)
- [Azure Database for MySQL Advanced Threat Protection](https://docs.microsoft.com/en-us/azure/mysql/concepts-data-access-and-security-threat-protection)

Similar to [Azure.SQL.ThreatDetection](https://github.com/microsoft/PSRule.Rules.Azure/blob/main/src/PSRule.Rules.Azure/rules/Azure.SQL.Rule.ps1#L36)

**Comment by bengeset96** [comment]
I'll take it.
