### ISSUE TITLE
[RULE] Migrate to App Gateway WAF policy

### ISSUE THREAD

**Issue by BernieWhite** [Azure/PSRule.Rules.Azure#2877]
### Suggested rule

App Gateway V2 supports two configuration modes for WAF:

1. Reference an existing WAF policy reference via `properties.firewallPolicy.id`.
2. Specify the WAF configuration via setting the `properties.webApplicationFirewallConfiguration`. This option is deprecated for retirement on 15 March 2027.

The rule should identify cases when `properties.webApplicationFirewallConfiguration` is configured and provide a recommendation to use a WAF policy instead.

### Pillar

Reliability

### Additional context

- https://azure.microsoft.com/updates/retirement-support-for-application-gateway-web-application-firewall-v2-configuration-is-ending/
- https://learn.microsoft.com/azure/templates/microsoft.network/applicationgateways
- https://azure.github.io/PSRule.Rules.Azure/en/rules/Azure.AppGw.MigrateV2/

**Comment by BenjaminEngeset** [comment]
:shipit:
