### ISSUE TITLE
[RULE] Migrate to Grafana 10

### ISSUE THREAD

**Issue by BernieWhite** [Azure/PSRule.Rules.Azure#2878]
### Suggested rule

Support for version 9 within managed grafana is deprecated and will retire on 31 August 2024.

### Pillar

Reliability

### Additional context

Resource provider is `Microsoft.Dashboard/grafana`.

- https://azure.microsoft.com/updates/action-recommended-update-to-using-grafana-version-10-for-azure-managed-grafana/
- https://learn.microsoft.com/azure/managed-grafana/how-to-upgrade-grafana-10
- https://learn.microsoft.com/azure/templates/microsoft.dashboard/grafana

Similar rules:

- https://azure.github.io/PSRule.Rules.Azure/en/rules/Azure.AppGw.MigrateV2/
- https://github.com/Azure/PSRule.Rules.Azure/blob/00e1ca9fecbb2654b9476f961eb1d81245adff9a/src/PSRule.Rules.Azure/rules/Azure.FrontDoorWAF.Rule.yaml#L75-L101

**Comment by BenjaminEngeset** [comment]
:shipit:
