### ISSUE TITLE
[RULE] Migrate to node.js 20 in App Services

### ISSUE THREAD

**Issue by BernieWhite** [Azure/PSRule.Rules.Azure#2879]
### Suggested rule

Node.js 18 support in App Service is depreciated and extended support will end on 30 April 2025.

Web apps should upgrade to node.js 20.

- For windows app services this is configured via the `WEBSITE_NODE_DEFAULT_VERSION` app setting.
  - Noting that export of app settings may not be permitted in some scenarios, so this rule should only fail when a `WEBSITE_NODE_DEFAULT_VERSION` setting is found and configured with a lower version then 20.
- For linux this is set via `linuxFxVersion`.

### Pillar

Reliability

### Additional context

- https://azure.microsoft.com/updates/action-required-upgrade-your-app-service-apps-to-node-20-lts-by-30-april-2025/
- https://github.com/Azure/app-service-linux-docs/blob/master/Runtime_Support/node_support.md#node-on-linux-app-service

**Comment by BenjaminEngeset** [comment]
:shipit:

I also think we have to do some special handling for App Services running on Windows as the `Microsoft.Web/sites/config` sub-resource overrides `properties.appSettings property` which can lead to some unexpected behavior.

**Comment by BenjaminEngeset** [comment]
@BernieWhite 

After starting working with this, I see that there are several scenarios that might have to be taken into consideration, if we want that.

Resources that come into play here are the following:

- `Microsoft.Web/sites` Applicable for both Windows and Linux scenarios.
- `Microsoft.Web/sites/config` Only applicable for Windows scenarios as this cannot contain `linuxFxVersion`.
- `Microsoft.Web/sites/slots` Applicable for both Windows and Linux scenarios.
- `Microsoft.Web/sites/slots/config` Only applicable for Windows scenarios as this cannot contain `linuxFxVersion`.

What do we want to cover? We are limited with the sub-resources scenarios as the `GetSubResources` function only traveres one level down.

**Comment by BernieWhite** [comment]
@BenjaminEngeset Correct. There is a few complexities to this based on the structure of the resource.

This example should be close to the cases that need to be tested: 

https://github.com/Azure/PSRule.Rules.Azure/blob/ad6ab981befdc149b22748e5e519552493b401d7/src/PSRule.Rules.Azure/rules/Azure.AppService.Rule.ps1#L42-L71
