### ISSUE TITLE
[RULE] Enable automatic instance repairs in Azure Virtual Machine Scale Sets

### ISSUE THREAD

**Issue by jeanchg** [Azure/PSRule.Rules.Azure#2895]
### Suggested rule

As per [APRL recommendation](https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/azure-resources/Compute/virtualMachineScaleSets/#enable-automatic-repair-policy), enabling automatic instance repairs in Azure Virtual Machine Scale Sets enhances application availability through a continuous health check and maintenance process.

Resource Type: **_microsoft.compute/virtualmachinescalesets_**
Property with expected value: **_properties.automaticRepairsPolicy.enabled==true_**

### Pillar

Reliability

### Additional context

This rule will be used to test against the AVM Bicep VMSS module.
@rainerhalan

**Comment by BernieWhite** [comment]
Thanks @jeanchg. I think there is some good linkage to: https://learn.microsoft.com/en-us/azure/well-architected/reliability/self-preservation

**Comment by BenjaminEngeset** [comment]
:shipit:
