### ISSUE TITLE
[RULE] Disable Force strictly even balance across zones in Azure Virtual Machine Scale Sets

### ISSUE THREAD

**Issue by jeanchg** [Azure/PSRule.Rules.Azure#2901]
### Suggested rule

As per [APRL recommendation](https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/azure-resources/Compute/virtualMachineScaleSets/#disable-force-strictly-even-balance-across-zones-to-avoid-scale-in-and-out-fail-attempts), disabling strictly even VM instance distribution across Availability Zones in VMSS improves scalability and flexibility, noting that uneven distribution may better serve application load demands despite the potential trade-off in resilience.

Resource Type: **_microsoft.compute/virtualmachinescalesets_**
Properties should **NOT** have the following values: **_properties.orchestrationMode == "Uniform"_** and **_properties.zoneBalance == true**

### Pillar

Reliability

### Additional context

[VMSS Custom Scale-in Policy in Reliability Hub](https://learn.microsoft.com/en-us/azure/reliability/reliability-virtual-machine-scale-sets?tabs=graph-4%2Cgraph-1%2Cgraph-2%2Cgraph-3%2Cgraph-5%2Cgraph-6%2Cportal#-set-virtual-machine-scale-sets-custom-scale-in-policies-to-default)

This rule will be used to test against the AVM Bicep VMSS module.
@rahalan

**Comment by BernieWhite** [comment]
@jeanchg Similar to #2902. Does this recommendation only apply in the case when `orchestrationMode` is `Uniform`. OR does it equally apply in the case of `Flexible`?

**Comment by BenjaminEngeset** [comment]
I can create the rule, but awaiting for alignment before constructing the rule body.

**Comment by jeanchg** [comment]
checking with @rahalan , will update shortly

**Comment by BenjaminEngeset** [comment]
Any update @jeanchg?

**Comment by rahalan** [comment]
@BenjaminEngeset @jeanchg @BernieWhite after reading thoroughly through the documentation, I see no reason, why this recommendation should only apply to uniform and not flexible as well. I would suggest to recommend it for flexible as well.
