### ISSUE TITLE
[RULE] Deploy VMSS across availability zones with VMSS Flex

### ISSUE THREAD

**Issue by jeanchg** [Azure/PSRule.Rules.Azure#2902]
### Suggested rule

As per [APRL recommendation](https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/azure-resources/Compute/virtualMachineScaleSets/#deploy-vmss-across-availability-zones-with-vmss-flex), when creating VMSS, implement availability zones as a protection measure for your applications and data against the rare event of datacenter failure.

Resource Type **_microsoft.compute/virtualmachinescalesets_**
Property with expected value **_array_length(zones) > 1_**

### Pillar

Reliability

### Additional context

[Reliability Hub](https://learn.microsoft.com/en-us/azure/reliability/reliability-virtual-machine-scale-sets?tabs=graph-4%2Cgraph-1%2Cgraph-2%2Cgraph-3%2Cgraph-5%2Cgraph-6%2Cportal#-deploy-virtual-machine-scale-sets-across-availability-zones-with-virtual-machine-scale-sets-flex)
[Create a Virtual Machine Scale Set that uses Availability Zones](https://learn.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-use-availability-zones?tabs=cli-1%2Cportal-2)
[Update scale set to add availability zones](https://learn.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-use-availability-zones?tabs=cli-1%2Cportal-2#update-scale-set-to-add-availability-zones)

**Comment by BernieWhite** [comment]
@jeanchg The documentation is unclear on the point of flexible vs uniform in your title.

Are we saying this is only a recommendation if the orchestration mode is `Flexible`?

**Comment by BenjaminEngeset** [comment]
I can create the rule, but awaiting for alignment before constructing the rule body.

**Comment by jeanchg** [comment]
checking with @rahalan , will update shortly

**Comment by BenjaminEngeset** [comment]
Any update @jeanchg?

**Comment by rahalan** [comment]
@BernieWhite @BenjaminEngeset @jeanchg I see no reason, why this should only apply for flexible. I would suggest to recommend it for uniform as well.
