### ISSUE TITLE
[RULE] Azure Firewall Should Be Deployed Across Availability Zones

### ISSUE THREAD

**Issue by jtracey93** [Azure/PSRule.Rules.Azure#2909]
### Suggested rule

Azure Firewall Should Be Deployed Across Availability Zones as per https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/azure-resources/Network/azureFirewalls/#deploy-azure-firewall-across-multiple-availability-zones

### Pillar

Reliability

**Comment by BenjaminEngeset** [comment]
:shipit:

**Comment by BenjaminEngeset** [comment]
Hi @BernieWhite,

Should we look for more than one member in the array, or should we specifically look for three members in the array?

**Comment by BernieWhite** [comment]
@BenjaminEngeset more then one.
