### ISSUE TITLE
[RULE] Update AKS tier to Standard

### ISSUE THREAD

**Issue by jeanchg** [Azure/PSRule.Rules.Azure#2911]
### Suggested rule

As per [APRL recommendation](https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/azure-resources/ContainerService/managedClusters/#update-aks-tier-to-standard), Production AKS clusters require the Standard tier for a financially backed SLA and enhanced node scalability, as the free service lacks these features.

Resource Type: **_microsoft.compute/managedclusters_**
Properties and expected values: **_sku.tier != "Standard"_**

### Pillar

Reliability

### Additional context

[Free, Standard and Premium pricing tiers for Azure Kubernetes Service (AKS) cluster management](https://learn.microsoft.com/en-us/azure/aks/free-standard-pricing-tiers)
[Kubernetes API Server SLA](https://learn.microsoft.com/en-us/azure/architecture/reference-architectures/containers/aks/baseline-aks?toc=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fazure%2Faks%2Ftoc.json&bc=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fazure%2Fbread%2Ftoc.json#kubernetes-api-server-sla)

**Comment by BenjaminEngeset** [comment]
@jeanchg

It appears there is already a rule that addresses this requirement. 

You can refer to the documentation here: 
https://azure.github.io/PSRule.Rules.Azure/en/rules/Azure.AKS.UptimeSLA

However, it might be beneficial to review the existing rule and update the documentation.

**Comment by jeanchg** [comment]
My bad, thank you @BenjaminEngeset !

**Comment by BernieWhite** [comment]
Sounds like we're good to close this one. Let me know if there is another reason to keep this open.
