### ISSUE TITLE
[RULE] Enable HA with zone redundancy

### ISSUE THREAD

**Issue by jeanchg** [Azure/PSRule.Rules.Azure#2914]
### Suggested rule

As per [APRL recommendation](https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/azure-resources/DBforMySQL/flexibleServers/#enable-ha-with-zone-redundancy), enable HA with zone redundancy on flexible server instances to deploy a standby replica in a different zone, offering automatic failover capability for improved reliability and disaster recovery.

Resource Type: **_microsoft.dbformysql/flexibleservers_**
Properties and expected values: **_highAvailability.mode == "ZoneRedundant"_**

### Pillar

Reliability

### Additional context

[High availability concepts in Azure Database for MySQL - Flexible Server](https://learn.microsoft.com/en-us/azure/mysql/flexible-server/concepts-high-availability)

**Comment by BernieWhite** [comment]
@BenjaminEngeset See this example. https://github.com/azure/psrule.rules.azure/blob/main/src/PSRule.Rules.Azure/rules/Azure.ContainerApp.Rule.ps1#L21-L33

We can use support for AZ in VMSS as a guide because it is a foundational service that needs to be present before AZ support is offered in PaaS services that build on top of these features.

**Comment by BenjaminEngeset** [comment]
> @BenjaminEngeset See this example. https://github.com/azure/psrule.rules.azure/blob/main/src/PSRule.Rules.Azure/rules/Azure.ContainerApp.Rule.ps1#L21-L33
> 
> We can use support for AZ in VMSS as a guide because it is a foundational service that needs to be present before AZ support is offered in PaaS services that build on top of these features.
> 
> But indeed call out that there might be false positives in the docs.

I understand! Great news. My earlier comment can now be disregarded since I have this information.

I'll create the rule.
