### ISSUE TITLE
[RULE] Enable custom maintenance schedule for MySQL 

### ISSUE THREAD

**Issue by prjelesi** [Azure/PSRule.Rules.Azure#2916]
### Suggested rule

As per APRL recommendation, we need to check if maintenance configuration exist https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/azure-resources/DBforMySQL/flexibleServers/#enable-custom-maintenance-schedule.

Resource Type: microsoft.dbformysql/flexibleservers

https://learn.microsoft.com/en-us/azure/mysql/flexible-server/how-to-maintenance-portal#specify-maintenance-schedule-options

### Pillar

Reliability

**Comment by BernieWhite** [comment]
https://learn.microsoft.com/en-gb/azure/well-architected/reliability/metrics

**Comment by BenjaminEngeset** [comment]
:shipit:
