### ISSUE TITLE
[RULE] Configure a customer-controlled maintenance window for SQL Database

### ISSUE THREAD

**Issue by BernieWhite** [Azure/PSRule.Rules.Azure#2956]
### Suggested rule

Azure periodically performs planned maintenance of SQL Database resources. During a maintenance event, databases are fully available but can be subject to short reconfigurations within availability Service Level Agreements (SLA) for SQL Database).

By configuring a customer-controlled maintenance window, you can schedule updates to occur during a preferred time, ideally outside business hours, minimizing disruptions.

### Pillar

Reliability

### Additional context

- https://learn.microsoft.com/en-us/azure/azure-sql/database/maintenance-window?view=azuresql
- https://learn.microsoft.com/azure/well-architected/reliability/metrics
- https://azure.github.io/PSRule.Rules.Azure/en/rules/Azure.MySQL.MaintenanceWindow/

**Comment by BenjaminEngeset** [comment]
:shipit:
