### ISSUE TITLE
[RULE]  Disable default outbound access for virtual machines

### ISSUE THREAD

**Issue by BenjaminEngeset** [Azure/PSRule.Rules.Azure#3001]
### Suggested rule

By default, virtual machines (VMs) created in a virtual network without explicit outbound connectivity are assigned a default outbound public IP address. This IP address enables outbound connectivity to the internet.

Why disable default outbound access?

- Security: Following the zero trust network security principle, it is not recommended to expose a virtual network to the internet by default.
- Explicit Connectivity: It is better to use explicit methods of connectivity rather than implicit ones for granting internet access to VMs.
- Ownership and Stability: The default outbound access IP is managed by Microsoft, and its ownership or address might change, potentially causing disruptions.

Enabling the private subnet feature on a subnet prevents VMs within that subnet from using default outbound access to connect to public endpoints.

This also applies to VMs within a scale set configured with uniform orchestration mode.

This feature is currently in preview.

### Pillar

Security

### Additional context

- [SE:06 Network controls](https://learn.microsoft.com/azure/well-architected/security/networking)
- [Default outbound access](https://learn.microsoft.com/azure/virtual-network/ip-services/default-outbound-access)
- [Azure deployment reference - Virtual Network](https://learn.microsoft.com/azure/templates/microsoft.network/virtualnetworks)
- [Azure deployment reference - Subnet](https://learn.microsoft.com/azure/templates/microsoft.network/virtualnetworks/subnets)

**Comment by BernieWhite** [comment]
@BenjaminEngeset this one is a little more nuanced.

When a customer starts deploying multiple workloads for most cases they should be thinking about using a VWAN or hub and spoke network with a central Azure Firewall or NVA for controlling east/ west and north/ south traffic. As a result, every subnet shouldn't have a NAT gateway attached. Realistically the number of internet egress points should be minimized.

You could say that anything in the VNET hub should have a NAT gateway, but even then, there is cases when this is not ideal.

- NAT Gateway is zonal, so you should deploy one in each AZ you deploy to, but with something like Azure Firewall that supports zone redundancy deploying a single NAT gateway (only one can be deployed in a subnet) could decrease the availablity of  

So, I'm not sure if we can reliability detect the cases from code the cases that should use a NAT gateway.

Did you have any further thoughts on this?
