### ISSUE TITLE
[RULE] Use Azure NAT gateway for outbound access for virtual machines

### ISSUE THREAD

**Issue by BenjaminEngeset** [Azure/PSRule.Rules.Azure#3003]
### Suggested rule

By default, virtual machines (VMs) created in a virtual network without explicit outbound connectivity are assigned a default outbound public IP address. This IP address enables outbound connectivity to the internet.

Default Routing Behavior:
The subnet has a system default route that routes traffic with the destination 0.0.0.0/0 to the internet.
Normally, when this route is chosen, the traffic is NATed using either a default public IP address or the VM’s public IP address (if it exists) before being sent to the internet.

Behavior with NAT Gateway:
Once a NAT gateway is associated with the subnet, the behavior changes. Although the system default route will still have the next hop set to the internet, traffic is first sent to the NAT gateway.
The NAT gateway receives the traffic from the VMs in the subnet, NATs the traffic using its own public IP address, and then sends it to the internet.

The recommended method is to use NAT gateway as the explicit method of public connectivity for virtual machines to ensure security, explicit connectivity, and stability.

Also highly relevant for AKS clusters.

### Pillar

Security

### Additional context

- [SE:06 Network controls](https://learn.microsoft.com/azure/well-architected/security/networking)
- [Azure NAT Gateway](https://learn.microsoft.com/azure/nat-gateway/nat-overview)
- [Associate a NAT gateway to the subnet](https://learn.microsoft.com/azure/load-balancer/load-balancer-outbound-connections#2-associate-a-nat-gateway-to-the-subnet)
- [Default outbound access](https://learn.microsoft.com/azure/virtual-network/ip-services/default-outbound-access)
- [Azure deployment reference - Virtual Network](https://learn.microsoft.com/azure/templates/microsoft.network/virtualnetworks)
- [Azure deployment reference - Subnet](https://learn.microsoft.com/azure/templates/microsoft.network/virtualnetworks/subnets)

**Comment by BernieWhite** [comment]
@BenjaminEngeset this one is a little more nuanced.

When a customer starts deploying multiple workloads for most cases they should be thinking about using a VWAN or hub and spoke network with a central Azure Firewall or NVA for controlling east/ west and north/ south traffic. As a result, every subnet shouldn't have a NAT gateway attached. Realistically the number of internet egress points should be minimized.

You could say that anything in the VNET hub should have a NAT gateway, but even then, there is cases when this is not ideal.

- NAT Gateway is zonal, so you should deploy one in each AZ you deploy to, but with something like Azure Firewall that supports zone redundancy deploying a single NAT gateway (only one can be deployed in a subnet) could decrease the availablity of  

So, I'm not sure if we can reliability detect the cases from code the cases that should use a NAT gateway.

Did you have any further thoughts on this?

**Comment by BenjaminEngeset** [comment]
> @BenjaminEngeset this one is a little more nuanced.
> 
> When a customer starts deploying multiple workloads for most cases they should be thinking about using a VWAN or hub and spoke network with a central Azure Firewall or NVA for controlling east/ west and north/ south traffic. As a result, every subnet shouldn't have a NAT gateway attached. Realistically the number of internet egress points should be minimized.
> 
> You could say that anything in the VNET hub should have a NAT gateway, but even then, there is cases when this is not ideal.
> 
> * NAT Gateway is zonal, so you should deploy one in each AZ you deploy to, but with something like Azure Firewall that supports zone redundancy deploying a single NAT gateway (only one can be deployed in a subnet) could decrease the availablity of
> 
> So, I'm not sure if we can reliability detect the cases from code the cases that should use a NAT gateway.
> 
> Did you have any further thoughts on this?

As discussed in the PR, I think we can close this issue. I fully agree with you.
