### ISSUE TITLE
[BUG] Azure.AppService.AvailabilityZone only detects premium by tier property

### ISSUE THREAD

**Issue by BernieWhite** [Azure/PSRule.Rules.Azure#3034]
### Existing rule

Azure.AppService.AvailabilityZone

### Description of the issue

When the plan SKU is deploy via `sku.name` the rule may incorrectly report the plan is not configured for a sone redundant tier.

### Reproduction

https://github.com/microsoft/PSRule/issues/1900

https://github.com/tsc-buddy/bicep-registry-modules/blob/ecac86acc0cad980c4a4773c07591a340c312d07/avm/res/web/serverfarm/main.bicep#L130-L133

### Version of PSRule

2.9.0

### Version of PSRule for Azure

1.38.0

**Comment by BenjaminEngeset** [comment]
Hi @BernieWhite. I understand the cause of the issue and I can engineer some better logical handling for it.
