### ISSUE TITLE
[BUG] GetBicepParamResources Exception when expanding Microsoft.Graph/groups resource

### ISSUE THREAD

**Issue by GaryRogersWoodmen** [Azure/PSRule.Rules.Azure#3062]
### Description of the issue

When adding Microsoft.Graph/groups resource I get an exception when running Invoke-PSRule.

### Error messages

Invoke-PSRule: Failed to expand bicep source 'C:\Users\userid\source\repository\IaC\tst.bicepparam'. Exception calling "GetBicepParamResources" with "2" argument(s): "Unable to expand resources because the source file 'C:\Users\user\source\repository\IaC\tst.bicepparam' was not valid. Object reference not set to an instance of an object."

### Reproduction

Add a Microsoft.Graph/groups resource to a main.bicep

```
resource permissionsGroup 'Microsoft.Graph/groups@v1.0' = {
  displayName: 'azure-testgroup'
  mailEnabled: false
  mailNickname: ''
  securityEnabled: true
  uniqueName: 'azure-testgroup'
}
```

### Version of PSRule

2.9.0

### Version of PSRule for Azure

1.38.0

### Additional context

Trying to add a group with Microsoft.Graph/groups for use in a role assignment. 

Looks mostly like this:

https://github.com/microsoftgraph/msgraph-bicep-types/blob/main/quickstart-templates/security-group-assign-azure-role/main.bicep

**Comment by BernieWhite** [comment]
Thanks for reporting the issue @GaryRogersWoodmen

**Comment by BernieWhite** [comment]
There is some differences with extensibility resources vs ARM resources. One key one is they don't really have an resource ID. This might be solved as extensibility matures with deployment stacks support.

Adding full support for testing of Microsoft Graph and other extensibility resources, would require a fairly major enhancement in it's current form and possible is out of scope for the PSRule for Azure project.

As a result, this issue will deal with resolving the bug that halts expansion for `.bicep` files that could contain a mix of extensibility and regular Azure resources.

A separate discussion thread will be opened for adding pre-flight support for Microsoft Graph to determine if there is community support for this feature and specific on use cases for alignment to WAF.

---

Discussion for support for Microsoft Graph is here: https://github.com/Azure/PSRule.Rules.Azure/discussions/3092
