### ISSUE TITLE
[RULE] Update documentation of Azure.ContainerApp.AvailabilityZone to include subnet requirement

### ISSUE THREAD

**Issue by ReneHezser** [Azure/PSRule.Rules.Azure#3068]
### Existing rule

Azure.ContainerApp.AvailabilityZone

### Description of the issue

Not specifying a workload will provision the service with a Consumption Plan, which does not support zoneRedundant = true
See https://github.com/Azure/bicep-registry-modules/blob/95ee1a36aac870b74568a78361ee68a488d4784c/avm/res/app/job/main.bicep#L90 and https://github.com/Azure/bicep-registry-modules/blob/95ee1a36aac870b74568a78361ee68a488d4784c/avm/res/app/job/tests/e2e/consumptionPlan/main.test.bicep#L48 for reference.

### Error messages

Error: AZR-000414: container-apps-environment-***acjmin001 failed Azure.ContainerApp.AvailabilityZone. Use Container Apps environments that are zone redundant to improve reliability.

### Reproduction

https://github.com/Azure/bicep-registry-modules/tree/main/avm/res/app/job/tests/e2e/consumptionPlan

### Version of PSRule

2.9.0

**Comment by BernieWhite** [comment]
Thanks for reporting the issue @ReneHezser

**Comment by BernieWhite** [comment]
@ReneHezser Can we confirm this with PG. Current guidance (https://learn.microsoft.com/azure/reliability/reliability-azure-container-apps) implies that V2 consumption plan and consumption only (without workload profile - v1) support zone redundancy.

> Azure Container Apps offers the same reliability support regardless of your plan type.
> Azure Container Apps uses [availability zones](https://learn.microsoft.com/en-us/azure/reliability/availability-zones-overview#zonal-and-zone-redundant-services) in regions where they're available. For a list of regions that support availability zones, see [Availability zone service and regional support](https://learn.microsoft.com/en-us/azure/reliability/availability-zones-service-support).

Also, when I deploy a consumption only environment the RP accepts the zone redundancy configuration.

Feel free to ping me offline or loop me into the internal discussion as required.

**Comment by ReneHezser** [comment]
Hi @BernieWhite,
Thanks for the hint. To enable zone redundancy with a consumption plan, a subnet needs to be used.
https://learn.microsoft.com/en-us/azure/reliability/reliability-azure-container-apps?tabs=azure-cli#enable-zone-redundancy-with-the-azure-cli

I'll go that way and close the issue.

**Comment by BernieWhite** [comment]
@ReneHezser As discussed, the rule works as expected, however further guidance on specific for consumption only plans would help future detection to be resolved. This issue will be updated to be a documentation update.

Error reported by ARM is:

> The environment network configuration is invalid: ZoneRedundant must be disabled if InfrastructureSubnetId is not provided.

---

Rule documentation should be updated to indicate that container apps zone redundancy feature requires a virtual network with an available subnet.

> To take advantage of availability zones, you must enable zone redundancy when you create a Container Apps environment. The environment must include a virtual network with an available subnet. To ensure proper distribution of replicas, set your app's minimum replica count to three.

https://learn.microsoft.com/azure/reliability/reliability-azure-container-apps?tabs=azure-cli#set-up-zone-redundancy-in-your-container-apps-environment
