### ISSUE TITLE
Add walk through for first time contributors

### ISSUE THREAD

**Issue by BernieWhite** [Azure/PSRule.Rules.Azure#3097]
Provide a walk through for first time contributors so they can easily onboard to the project and start contributing.

**Comment by that-ar-guy** [comment]
hey can i take this up

**Comment by BernieWhite** [comment]
Thanks @that-ar-guy. That would be great. Let me know when you have a PR or if you have additional questions. Some information can be found in https://github.com/Azure/PSRule.Rules.Azure/blob/main/CONTRIBUTING.md, but it might not be clear.

**Comment by BernieWhite** [comment]
@that-ar-guy Let's add a new file under `docs/license-contributing/` maybe `get-started-contributing.md` or something similar so that it will be published under https://azure.github.io/PSRule.Rules.Azure/license-contributing/.

We can link that in `CONTRIBUTING.md` once you're done.

**Comment by that-ar-guy** [comment]
hey @BernieWhite, I’ve opened a [pull request](https://github.com/Azure/PSRule.Rules.Azure/pull/3188) . As I’m new to open source, your review and any feedback would be invaluable in helping me improve. Please take your time, and thank you in advance for your guidance!
