### ISSUE TITLE
[FEATURE] Create a `CONTRIBUTORS.md` File

### ISSUE THREAD

**Issue by that-ar-guy** [Azure/PSRule.Rules.Azure#3197]
I propose adding a CONTRIBUTORS.md file to recognize and document the contributions of all collaborators in the project.

**Details**
The file can:

- List contributors' names, GitHub handles, and their contributions.
- Use tools like [All Contributors](https://allcontributors.org/) for automation.
- Encourage community involvement by showcasing recognition.

**Benefits**

- Promotes transparency and inclusivity.
- Motivates new contributors.
- Helps maintain a history of contributions.

### Alternatives

A GitHub Contributors Graph or a section in the `README.md` listing contributors could be considered as alternatives.

### Additional context

This feature will encourage better collaboration and maintain a record of community contributions.

**Comment by BernieWhite** [comment]
Hi @that-ar-guy

We do this currently by the change log docs/CHANGELOG-v1.md.

This way contributions are included in each release. Feel free to add an update for your last PR.

**Comment by that-ar-guy** [comment]
Got it, thanks for clarifying! That approach works well. I’m good with it and won’t add more at this point.
