### ISSUE TITLE
Update CI pipeline to use Pester v5

### ISSUE THREAD

**Issue by BernieWhite** [Azure/PSRule.Rules.Azure#395]
Pester v5 has just been released and introduced a number of breaking changes. These changes are not compatible with the current pipeline configuration.

For the moment Pester v4 will be used, however it should be upgraded to v5 at some time in the future.

**Comment by ArmaanMcleod** [comment]
I can probably help with this. Will need o convert the existing pester v4 tests to use pester v5 `BeforeAll/BeforeDiscovery` scoping and some other things. Will be a big job but I'll see how I go and send a PR for review 🙂 .
