### ISSUE TITLE
Check if Multitenant Hosting Rights are used for Windows client VMs

### ISSUE THREAD

**Issue by BernieWhite** [Azure/PSRule.Rules.Azure#432]
# Rule request

## Suggested rule change

Multitenant Hosting Rights can be used for Windows 10 client VMs to reduce VM running costs.

## Applies to the following

The rule applies to the following:

- Resource type: **Microsoft.Compute/virtualMachines**

## Additional context

[How to deploy Windows 10 on Azure with Multitenant Hosting Rights](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/windows-desktop-multitenant-hosting-deployment)

**Comment by BenjaminEngeset** [comment]
Upcoming PR from me to be expected :shipit:.
