### ISSUE TITLE
Enable caching to accelerate Front Door traffic

### ISSUE THREAD

**Issue by BernieWhite** [Azure/PSRule.Rules.Azure#548]
# Rule request

## Suggested rule change

Use caching for each Front Door route rule to reduce latency and minimize calls to backend systems.

## Applies to the following

The rule applies to the following:

- Resource type: **Microsoft.Network/frontDoors**

## Additional context

[Caching with Azure Front Door](https://docs.microsoft.com/azure/frontdoor/front-door-caching)

**Comment by bengeset96** [comment]
@BernieWhite 

Since almost two years has passed by and this is left untouched, I'd like to contribute to this one.

Front Door declaration without caching is something we should not have unless explicitly stated as this is one of the main reasons using `Front Door` in the first place.
