### ISSUE TITLE
Notifications are configured for Azure Backup

### ISSUE THREAD

**Issue by BernieWhite** [Azure/PSRule.Rules.Azure#6]
Check that backup configuration has email notification settings configured in Recovery Services vault.

**Comment by ms-sambell** [comment]
Hey @BernieWhite, 

I just wanted to check with you if we need this rule. The resource provider type is:
`Microsoft.RecoveryServices/vaults/monitoringConfigurations/notificationConfiguration`

I got this via looking at the REST call made when configuring the backup email in the portal. I can't find a reference to resource type in the ARM templates documents. I've also browsed through all the sub-resource types for RecoveryServices to see if there's an option to set the BackupAlert config, but I couldn't find one. 

The backup alert for a RSV can't be exported in the template and isn't displayed when I query all resources in my subscription.
` {   
            "type": "Microsoft.RecoveryServices/vaults/monitoringConfigurations/notificationConfiguration",
            "apiVersion": "2017-07-01-preview",
            "name": "newvaultdemo",
            "properties": {
                "areNotificationsEnabled": true,
                "hasValidEmailAddresses": true,
                "frequencyDetails": {
                    "frequencyType": "Immediate",
                    "frequencyValue": 1
                },
                "severitiesToNotifyFor": [
                    "Critical"
                ],
                "additionalRecipients": [
                    "example@email.com"
                ]
            }
        }`


If I use the information in the initial REST call, I have a decent idea of what the ARM resource would look like (although I'm still fixing the resource segments. 



Do you still want me to set this? I think this functionality is moving to the [Backup Center](https://docs.microsoft.com/en-us/azure/backup/backup-center-monitor-operate#alerts)

**Comment by BernieWhite** [comment]
@ms-sambell Yes, I think in this case it makes sense to close this issue. The alerting is moving to Azure Monitor.
