### ISSUE TITLE
VMs in an availablity set should use a load balancer or application gateway

### ISSUE THREAD

**Issue by BernieWhite** [Azure/PSRule.Rules.Azure#67]
# Rule request

## Suggested rule change

VMs in an availability set should use a load balancer or application gateway to distribute traffic as part of a backend pool.

## Applies to the following

The rule applies to the following:

- Resource type: **Microsoft.Compute/virtualMachines**

**Comment by bengeset96** [comment]
@BernieWhite 
 
So it will be that when `properties.availabilitySet` has an valid value, then we should check for that `properties.networkProfile.networkInterfaceConfigurations.properties.ipConfigurations.properties.applicationGatewayBackendAddressPools` or `properties.networkProfile.networkInterfaceConfigurations.properties.ipConfigurations.properties.loadBalancerBackendAddressPools` has an valid value?

**Comment by BenjaminEngeset** [comment]
@BernieWhite Bump :)
