### ISSUE TITLE
AKS network security group uses managed rules

### ISSUE THREAD

**Issue by BernieWhite** [Azure/PSRule.Rules.Azure#8]
# Rule request

## Suggested rule change

Check if NSG created by AKS has additional custom rules added. AKS adds and removes rules from this NSG automatically.

## Applies to the following

The rule applies to the following:

- Resource type: **Microsoft.Network/networkSecurityGroups**

**Comment by ms-sambell** [comment]
Adding notes:

Check the NSG name prefix = "aks-" and suffix "-nsg"

The rule name will be like: 

<img width="375" alt="image" src="https://user-images.githubusercontent.com/93104336/190952156-4aa4a453-326c-4b17-a189-f6d16e14b526.png">
