### ISSUE TITLE
Rule does not detect more restrictive NSG rules

### ISSUE THREAD

**Issue by vicperdana** [Azure/PSRule.Rules.Azure#831]
https://github.com/Azure/PSRule.Rules.Azure/blob/536f1a5dc534a1cdc4633f9c6c0caa2a1dc1696a/src/PSRule.Rules.Azure/rules/Azure.VirtualNetwork.Rule.ps1#L166

If NSG has rules to deny outbound traffic from VNET to VNET and Internet, the rule should detect and mark the validation to "Pass". 

![image](https://user-images.githubusercontent.com/7114832/125779980-a977c331-5565-407b-b756-0cff72b98d4a.png)

**Comment by BernieWhite** [comment]
Awesome. Thanks @vicperdana

**Comment by BernieWhite** [comment]
In the spirit of lateral traversal, I don't think management ports outbound to the internet is a concern. If we block management traffic to `VirtualNetwork` or `*` via either `3389`, `22`, or `*` I think that addresses the requirement.

**Comment by vicperdana** [comment]
Agreed.
