### ISSUE TITLE
Review and update Container Registry rule docs

### ISSUE THREAD

**Issue by BernieWhite** [Azure/PSRule.Rules.Azure#868]
Review and update rule documentation with template and bicep examples.

Find documentation here: https://azure.github.io/PSRule.Rules.Azure/en/rules/resource/#container-registry

Find source here: https://github.com/Azure/PSRule.Rules.Azure/tree/main/docs/en/rules

**Comment by pazdedav** [comment]
I found the following rules in `Azure.ACR` rules without code samples:

- [GeoReplica](https://azure.github.io/PSRule.Rules.Azure/en/rules/Azure.ACR.GeoReplica/)
- [ImageHealth](https://azure.github.io/PSRule.Rules.Azure/en/rules/Azure.ACR.ImageHealth/)
- [Name](https://azure.github.io/PSRule.Rules.Azure/en/rules/Azure.ACR.Name/)
- [Usage](https://azure.github.io/PSRule.Rules.Azure/en/rules/Azure.ACR.Usage/)

I will focus on those during the **Microsoft Hackathon**.
