### ISSUE TITLE
VMs stopped but not deallocated

### ISSUE THREAD

**Issue by BernieWhite** [Azure/PSRule.Rules.Azure#88]
# Rule request

## Suggested rule change

VMs that are stopped but not deallocated are still charged for compute. In general virtual machines should be deallocated when not in use.

Edge cases can include domain controllers and VMs for imaging.

## Applies to the following

The rule applies to the following:

- Resource type: **Microsoft.Compute/virtualMachines**

**Comment by dcrreynolds** [comment]
Hi @BernieWhite, if I am understanding correctly this rule would only apply to deployed VMs (not ARM/Bicep analysis) and there would first need to be an update to the data gathered during the export because it doesn't include it today. Is that the intention of this issue?

**Comment by BernieWhite** [comment]
@dcrreynolds Correct. The information is not collected today.
