### ISSUE TITLE
Collect audit logs for AKS clusters

### ISSUE THREAD

**Issue by BernieWhite** [Azure/PSRule.Rules.Azure#882]
# Rule request

## Suggested rule change

Enable capture of security-based audit logs on AKS clusters.

[Security audits](https://docs.microsoft.com/azure/architecture/framework/security/monitor-audit)
[Collect resource logs](https://docs.microsoft.com/azure/aks/monitor-aks#collect-resource-logs)

## Applies to the following

The rule applies to the following:

- Resource type: **Microsoft.ContainerService/managedClusters**

**Comment by ArmaanMcleod** [comment]
@BernieWhite From https://docs.microsoft.com/en-us/azure/aks/monitor-aks#collect-resource-logs would we make this rule follow the table below to make sure what resource diagnostic logs need to be turned on. 

<html>
<body>


Category | Enable? | Destination
-- | -- | --
cluster-autoscaler | Enable if autoscale is enabled | Log Analytics workspace
guard | Enable if Azure Active Directory is enabled | Log Analytics workspace
kube-apiserver | Enable | Log Analytics workspace
kube-audit | Enable | Azure storage. This keeps costs to a minimum yet retains the audit logs if they're required by an auditor.
kube-audit-admin | Enable | Log Analytics workspace
kube-controller-manager | Enable | Log Analytics workspace
kube-scheduler | Disable |  
AllMetrics | Enable | Log Analytics workspace


</body>
</html>

I think `cluster-autoscaler` should only be turned on if `enableAutoScaling` is `True`, and `guard` only if `Properties.aadProfile.enableAzureRbac`(or maybe another AAD property?) is `True`. Unsure why `kube-scheduler` is recommended to be disabled, I would assume that it would important to turn that on. 

Also what would the rule be named? Perhaps something like `Azure.AKS.Logs`? Seems to be similar to other rules like `Azue.FrontDoor.Logs` and `Azure.KeyVault.Logs`. 

Can probably add the diagnostic settings from `Get-AzDiagnosticSetting` as a subresource:

```json
{
  "Location": null,
  "Tags": null,
  "StorageAccountId": null,
  "ServiceBusRuleId": null,
  "EventHubAuthorizationRuleId": null,
  "EventHubName": null,
  "Metrics": [
    {
      "TimeGrain": null,
      "Category": "AllMetrics",
      "Enabled": true,
      "RetentionPolicy": "Microsoft.Azure.Management.Monitor.Models.RetentionPolicy"
    }
  ],
  "Logs": [
    {
      "Category": "kube-apiserver",
      "Enabled": true,
      "RetentionPolicy": "Microsoft.Azure.Management.Monitor.Models.RetentionPolicy"
    },
    {
      "Category": "kube-audit",
      "Enabled": true,
      "RetentionPolicy": "Microsoft.Azure.Management.Monitor.Models.RetentionPolicy"
    },
    {
      "Category": "kube-audit-admin",
      "Enabled": true,
      "RetentionPolicy": "Microsoft.Azure.Management.Monitor.Models.RetentionPolicy"
    },
    {
      "Category": "kube-controller-manager",
      "Enabled": true,
      "RetentionPolicy": "Microsoft.Azure.Management.Monitor.Models.RetentionPolicy"
    },
    {
      "Category": "kube-scheduler",
      "Enabled": true,
      "RetentionPolicy": "Microsoft.Azure.Management.Monitor.Models.RetentionPolicy"
    },
    {
      "Category": "cluster-autoscaler",
      "Enabled": true,
      "RetentionPolicy": "Microsoft.Azure.Management.Monitor.Models.RetentionPolicy"
    },
    {
      "Category": "guard",
      "Enabled": true,
      "RetentionPolicy": "Microsoft.Azure.Management.Monitor.Models.RetentionPolicy"
    }
  ],
  "WorkspaceId": "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourcegroups/defaultresourcegroup-eau/providers/microsoft.operationalinsights/workspaces/defaultworkspace-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx-eau",
  "LogAnalyticsDestinationType": null,
  "Id": "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourcegroups/k8s-aks-cluster-rg/providers/microsoft.containerservice/managedclusters/k8s-aks-cluster/providers/microsoft.insights/diagnosticSettings/metrics",
  "Name": "metrics",
  "Type": "Microsoft.Insights/diagnosticSettings"
}
```

**Comment by BernieWhite** [comment]
@ArmaanMcleod Diagnostics and platform monitoring are a separate concern (Operational Excellence). Let's create a separate issue/ rule for that. If they are a rule, customers have more granularity if they disable the rule. Also, the documentation would be aligned to a different WAF pillar.

For security auditing, we should make sure that the following are logged:

- `kube-audit-admin` or `kube-audit` - `kube-audit-admin` is a reduced set that overlaps with `kube-audit` so only one of them is required. 
- `guard`

Yes, something like the Key Vault and Front Door logs in terms of naming and implementation. You could be more specific something like `Azure.AKS.AuditLogs` since relooking at those names they are a little too generic.

**Comment by chaoscreater** [comment]
Does anyone know from a security perspective, is enabling kube-audit-admin logs enough to scan for security related events, or should we also enable Defender for Containers? Is there an overlap if you have both enabled?
