### ISSUE TITLE
Collect platform logs for AKS clusters

### ISSUE THREAD

**Issue by BernieWhite** [Azure/PSRule.Rules.Azure#922]
# Rule request

## Suggested rule change

Enable capture of platform diagnostics logs.

[Platform monitoring](https://docs.microsoft.com/azure/architecture/framework/devops/monitoring#platform-monitoring)
[Collect resource logs](https://docs.microsoft.com/azure/aks/monitor-aks#collect-resource-logs)

## Applies to the following

The rule applies to the following:

- Resource type: **Microsoft.ContainerService/managedClusters**

Related to #882

**Comment by ArmaanMcleod** [comment]
@BernieWhite Should we call this rule `Azure.AKS.PlatformLogs` to be more explicit?

Also just checking if we would cover all these log categories which are not included in `Azure.AKS.AuditLogs`:
- cluster-autoscaler
- kube-apiserver
- kube-controller-manager
- kube-scheduler

And metric:s
- AllMetrics

**Comment by BernieWhite** [comment]
@ArmaanMcleod Make sense to me, that is the recommended starting point.

You could make it configurable. Some of these logs are considerable it's fairly likely that some customers would want to be selective about the list.

**Comment by ArmaanMcleod** [comment]
@BernieWhite No worries.

I can probably create a configuration like this to enable/disable the catogories inside the rule:

```pwsh
AZURE_AKS_ENABLED_PLATFORM_LOG_CATEGORIES = @{
        Logs = @{
            'cluster-autoscaler' = $True
            'kube-apiserver' = $True
            'kube-controller-manager' = $True
            'kube-scheduler' = $True
        }
        Metrics = @{
            'AllMetrics' = $True
        }
    }
```

**Comment by BernieWhite** [comment]
@ArmaanMcleod You could try it as an array of categories using GetStringValues. That might be slightly cleaner to configure.

https://github.com/microsoft/PSRule/blob/main/docs/concepts/PSRule/en-US/about_PSRule_Variables.md#configuration

https://github.com/microsoft/PSRule.Rules.CAF/blob/main/src/PSRule.Rules.CAF/rules/Baseline.Rule.yaml
