### ISSUE TITLE
VPN Gateways should use availability zones for regions that support it

### ISSUE THREAD

**Issue by BernieWhite** [Azure/PSRule.Rules.Azure#926]
# Rule request

## Suggested rule change

If availability zones are available in the VPN gateway region, we should deploy an AZ SKU.

[Use zone aware services](https://docs.microsoft.com/azure/architecture/framework/resiliency/design-best-practices#use-zone-aware-services)

## Applies to the following

The rule applies to the following:

- Resource type: **Microsoft.Network/virtualNetworkGateways**

## Additional context

Related to #880.

**Comment by ArmaanMcleod** [comment]
@BernieWhite Given VPN gateways control availability zones via Public IPs, would we check if the associated public IP is zone redundant for this rule? Or would this just be left to the `Azure.PublicIP.AvailabilityZone` rule I created?

```json
{
            "apiVersion": "2020-11-01",
            "name": "[parameters('name')]",
            "type": "Microsoft.Network/virtualNetworkGateways",
            "location": "[parameters('location')]",
            "dependsOn": [
                "Microsoft.Resources/deployments/vpn-gw-vnet-20210922163822",
                "[concat('Microsoft.Network/publicIPAddresses/', parameters('newPublicIpAddressName'))]"
            ],
            "tags": {},
            "properties": {
                "gatewayType": "[parameters('gatewayType')]",
                "ipConfigurations": [
                    {
                        "name": "default",
                        "properties": {
                            "privateIPAllocationMethod": "Dynamic",
                            "subnet": {
                                "id": "[parameters('subnetId')]"
                            },
                            "publicIpAddress": {
                                "id": "[resourceId('vpn-gw-rg', 'Microsoft.Network/publicIPAddresses', parameters('newPublicIpAddressName'))]"
                            }
                        }
                    }
                ],
                "vpnType": "[parameters('vpnType')]",
                "vpnGatewayGeneration": "[parameters('vpnGatewayGeneration')]",
                "sku": {
                    "name": "[parameters('sku')]",
                    "tier": "[parameters('sku')]"
                }
            }
        }
```

VPN gateway type AZ SKUs:
- VpnGw1AZ
- VpnGw2AZ
- VpnGw3AZ
- VpnGw4AZ
- VpnGw5AZ

ExpressRoute gateway type AZ SKUs:
- ErGw1AZ
- ErGw2AZ
- ErGw3AZ

**Comment by BernieWhite** [comment]
@ArmaanMcleod I think checking in Virtual network gateway sku in isolation is fine as there is already a rule for public IPs, it would be flagged.

But it might we worthwhile double checking the help content on the public ip rule to ensure it is clear that dependant resources will not be able to take full advantage of zone redundancy if deployed in a different way. But I have a feeling ARM will fail the deployment if a user bypasses rules and tries to do it anyway.

**Comment by ArmaanMcleod** [comment]
Thanks @BernieWhite. I think checking VPN/ExpressRoute gateway in isolation is simplest. 

Was thinking of splitting the rules like this:

```powershell
# Synopsis: 
Rule 'Azure.VNG.VPNAvailabilityZone' -Type 'Microsoft.Network/virtualNetworkGateways' -If { IsVPNGateway } -Tag @{ release = 'GA'; ruleSet = '2021_12'; } {
    $Assert.Match($TargetObject, 'Properties.sku.name', '^VpnGw[1-5]AZ$');
}

# Synopsis: 
Rule 'Azure.VNG.ERAvailabilityZone' -Type 'Microsoft.Network/virtualNetworkGateways' -If { IsERGateway } -Tag @{ release = 'GA'; ruleSet = '2021_12'; } {
    $Assert.Match($TargetObject, 'Properties.sku.name', '^ErGw[1-3]AZ$')
}
```

Or would you prefer if both gateway types were captured in the same rule like this:

```powershell
# Synopsis: 
Rule 'Azure.VNG.AvailabilityZone' -Type 'Microsoft.Network/virtualNetworkGateways' -Tag @{ release = 'GA'; ruleSet = '2021_12'; } {
    if (IsVPNGateway) {
        $Assert.Match($TargetObject, 'Properties.sku.name', '^VpnGw[1-5]AZ$');
    }
    elseif (IsERGateway) {
        $Assert.Match($TargetObject, 'Properties.sku.name', '^ErGw[1-3]AZ$')
    }
}
```
