### ISSUE TITLE
Rename Azure.VM.NICAttached

### ISSUE THREAD

**Issue by BernieWhite** [Azure/PSRule.Rules.Azure#933]
The rule name no longer makes sense as `Microsoft.Network/networkInterfaces` can be used by other services instead of just VMs.

A more generic name just as `Azure.NIC.Attached` is a better idea.

Also applies to: `Azure.VM.UniqueDns` and `Azure.VM.NICName` which all related to `Microsoft.Network/networkInterfaces` resources.

Renaming a rule is a breaking change so this will need to wait until the next major version.

Related to #932 

---

**Update 2023-12-07**

Previously this was only a breaking change. Now aliases in PSRule allows the change to be made earlier with an alias that points back to the old rule. #2574 

From v2 the aliases can be removed.

**Comment by bengeset96** [comment]
@BernieWhite 

Should we move the ones that are not specific to VM only in `VM.Rule.ps1` and `VM.Rule.yaml` to a more general one? Since NICs for an instance can be used for many other services. Was starting on this task, but felt weird to rename it without moving.

**Comment by BernieWhite** [comment]
@BenjaminEngeset Agree we should move the rule too. I think we can put it into `NIC.Rule.ps1` or `NIC.Rule.yaml`.

**Comment by BernieWhite** [comment]
Rule documentation now supporting linking and redirecting rule aliases. So now there is no specific need to clean up the aliases and implement this breaking change.
