### ISSUE TITLE
Limit public access for Azure Cache for Redis instances

### ISSUE THREAD

**Issue by BernieWhite** [Azure/PSRule.Rules.Azure#935]
# Rule request

## Suggested rule change

Limit public network access when private endpoints are configured by ensuring `publicNetworkAccess` is `Disabled`.

## Applies to the following

The rule applies to the following:

- Resource type: **Microsoft.Cache/Redis**

## Additional context

[Azure Cache for Redis with Azure Private Link](https://docs.microsoft.com/azure/azure-cache-for-redis/cache-private-link)

**Comment by ArmaanMcleod** [comment]
@BernieWhite I think this rule could also work for #934, given if `publicNetworkAccess` is `Disabled` then private endpoints are exclusively used.

**Comment by BernieWhite** [comment]
@ArmaanMcleod My understanding of this property is that if private endpoints are not configured, `publicNetworkAccess` can not be set. It is automatically set to `Disabled` when a private endpoint is created. However once a private endpoint is created the `publicNetworkAccess` can be forced to `Enabled`.

But could be wrong.

For this reason I think we still need to check both.

**Comment by ArmaanMcleod** [comment]
@BernieWhite Did a quick test and if you force public access to be enabled then the private endpoint is removed if public access was previously disabled. Seems that a `Azure.Redis.PublicNetworkAccess` rule is enough for both cases.

**Comment by BernieWhite** [comment]
@ArmaanMcleod So you are thinking that we can close #934 as duplicate?

**Comment by ArmaanMcleod** [comment]
@BernieWhite I think that should be fine. Can reopen it if I find that there is a difference between the rules.

**Comment by BernieWhite** [comment]
@ArmaanMcleod Sure. I'm good with that.
