### ISSUE TITLE
Load balancers should use Standard SKU

### ISSUE THREAD

**Issue by ArmaanMcleod** [Azure/PSRule.Rules.Azure#957]
# Rule request

## Suggested rule change

Load balancers should use Standard SKU for production workloads.

## Applies to the following

The rule applies to the following:

- Resource type: Microsoft.Network/loadBalancers

## Additional context

Related to #927

**Comment by ArmaanMcleod** [comment]
@BernieWhite Do you think this should go under the Operation Excellence pillar with Deployment category? Also should we name it as `Azure.LB.UseStandardSKU`? Or just `Azure.LB.SKU`?

**Comment by BernieWhite** [comment]
@ArmaanMcleod Name looks good. I'd suggest that this one also can go under Reliability. [ref](https://docs.microsoft.com/azure/architecture/framework/resiliency/design-requirements#meet-application-platform-requirements).

The PnP team has been realigning a fair bit of the WAF content so some rules that may have previously been under Operational Excellence might need to change.
