### ISSUE TITLE
Public IPs should use availability zones for regions that support it

### ISSUE THREAD

**Issue by BernieWhite** [Azure/PSRule.Rules.Azure#958]
# Rule request

## Suggested rule change

If availability zones are available in the region, we should deploy as zone redundant.

[Use zone aware services](https://docs.microsoft.com/azure/architecture/framework/resiliency/design-best-practices#use-zone-aware-services)

## Applies to the following

The rule applies to the following:

- Resource type: **Microsoft.Network/publicIPAddresses**

## Additional context

Related to #927.

**Comment by ArmaanMcleod** [comment]
@BernieWhite With this one, should we do the same behaviour as `Azure.LB.AvailabilityZone`. Public IPs can be zone-redundat, contstrained to a single zone(zonal) or have no zone.

public IP zones are in `Microsoft.Network/publicIpAddresses` provider. 

Wondering if we should apply the same behavior as `Azure.LB.AvailabilityZone`, but also add a check to ensure no zone/single zone public IPs are not in the providers zone mappings.

**Comment by BernieWhite** [comment]
@ArmaanMcleod Yes, we should only process the rule if it is a standard public IP. In terms of zone configuration similar to LB however we might need to guidance on this https://docs.microsoft.com/en-us/azure/virtual-network/public-ip-addresses#standard

> Can be zone-redundant (which is advertised from all three zones), zonal (which is guaranteed in a specific pre-selected availability zone), or "no-zone" (which isn't associated with a specific pre-selected availability zone). To learn more about availability zones, see Availability zones overview and Standard Load Balancer and Availability Zones. Zone redundant IPs can only be created in regions where three availability zones are live. IPs created before zones are live won't be zone redundant.

I interpret this as no-zone not being zone redundant.
